### PR TITLE
[openpathsampling] 0.9.1

### PR DESCRIPTION
**Pull request by dwhswenson**
Now to see whether I'm doing this correctly....

### CODE REVIEW

**Comment by dwhswenson** [comment]
Huh. Not passing the Mac build due to a lack of `tlmgr` (we don't even get to start building packages). Looks like `brew` isn't behaving the way it used to, either. I don't see how my changes could have caused this.

I notice the following difference between my build (https://travis-ci.org/omnia-md/conda-recipes/jobs/165013204) and the last nightly (https://travis-ci.org/omnia-md/conda-recipes/jobs/164804302) (line 4 in each):

Mine:
```
instance: ff11cdf5-4508-4dba-9d4e-e1202d4c62e1:travis-ci-osx10.11-xcode7.3-1475505633
```

Previous:
```
instance: 9a29c332-3ff9-416e-a274-42a3f85f6eb4:travis-ci-osx10.9-xcode6.1-1472151920
```

See also https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

**Comment by jchodera** [comment]
Crap.

**Comment by jchodera** [comment]
To get the old XCode version, I think you want to add
```
osx_image: beta-xcode6.1
```
though this will only work until 31 Oct 2016, at which point we have to upgrade.

See [here](https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions).

**Comment by dwhswenson** [comment]
Merging in @jchodera's fix in #606 gets the new OPS version bump to pass, too!

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
