### PR TITLE
cluster_utils renamed to clusterutils

### PR DESCRIPTION
**Pull request by danielparton**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Do you need to do a new release and update the git-tag on `clusterutils`?  E.g. 0.1.1?

**Comment by danielparton** [comment]
Yeah was just wondering how to do that

**Comment by danielparton** [comment]
0.1.1 makes sense - I'll do that

**Comment by danielparton** [comment]
Should be good to go now (pending Travis if necessary)

**Pull request merged**
