### PR TITLE
conda recipe for ParmEd

### PR DESCRIPTION
**Pull request by swails**
Did I do this right?

### CODE REVIEW

**Comment by rmcgibbo** [comment]
yeah, looks correct to me.

**Comment by swails** [comment]
Do I need to do anything inside ParmEd's repo?

**Comment by kyleabeauchamp** [comment]
Nope

**Comment by swails** [comment]
Sweet.

**Comment by kyleabeauchamp** [comment]
Jenkins dashboard is here: 

https://jenkins.choderalab.org/

**Comment by rmcgibbo** [comment]
Does parmed work on windows? If not, we can add a skip file.

**Comment by swails** [comment]
It's pure-python.

**Comment by swails** [comment]
Well, it has a single extension, but that can be excluded if it doesn't compile (it just speeds up prmtop parsing).

**Comment by rmcgibbo** [comment]
Sounds good. I'll check back on the windows build soon. https://ci.appveyor.com/project/rmcgibbo/conda-recipes. It usually takes about an hour for the appveyor VM to be provisioned.

**Comment by kyleabeauchamp** [comment]
OK, I took a look at logs and there's some shit going down.  

OSX:
```
Traceback (most recent call last):
  File "./conda-build-all", line 295, in <module>
    main()
  File "./conda-build-all", line 76, in main
    execute(args, p)
  File "./conda-build-all", line 274, in execute
    if package_exists_locally(recipe, python=python, numpy=numpy):
  File "./conda-build-all", line 152, in package_exists_locally
    filename = conda_build_output(recipe_path, python, numpy)
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/site-packages/conda/utils.py", line 120, in __call__
    value = self.func(*args, **kw)
  File "./conda-build-all", line 147, in conda_build_output
    '--numpy', numpy, recipe_path]).strip()
  File "/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/miniconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['conda-build', '--output', '--python', '27', '--numpy', '18', u'/Users/jenkins-slave/workspace/conda-omnia-release-osx-2/conda-recipes/ParmEd']' returned non-zero exit status 1
Error: package/name must be lowercase, got: u'ParmEd'
```

**Comment by kyleabeauchamp** [comment]
On linux, it also seems to not be building, but I don't have a helpful message.  There's lots of failures of other packages with dependency issues (e.g. bhmm).  The only relevant thing I saw was this:

```
Traceback (most recent call last):
  File "./conda-build-all", line 295, in <module>
    main()
  File "./conda-build-all", line 76, in main
    execute(args, p)
  File "./conda-build-all", line 269, in execute
    metadata = MetaData(recipe)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 255, in __init__
    assert isdir(path)
AssertionError
Build step 'Execute shell' marked build as failure
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
```

**Comment by rmcgibbo** [comment]
Well, the first step is probably to try changing the package name to lowercase...

**Comment by kyleabeauchamp** [comment]
After my last two pulls, it seems to have built on OSX. 

Note to @swails: now that there are packages online, if we want to overwrite them with a modified recipe, we would need to increment the build number in the recipe.

**Comment by kyleabeauchamp** [comment]
OK, looks like we have linux packages too: https://binstar.org/omnia/parmed/files

**Comment by jchodera** [comment]
Apologies for the `bhmm` issues.  I've been trying to figure out what is going on there, with no luck so far.

**Pull request merged**
