### PR TITLE
msmb_data

### PR DESCRIPTION
**Pull request by cxhernandez**
package containing testing data for MSMBuilder

### CODE REVIEW

**Comment by cxhernandez** [comment]
bump @jchodera

**Comment by jchodera** [comment]
Sorry for the delay! 

I've just given you admin access @cxhernandez so that I don't slow you down again.

(Thanks @rmcgibbo!)

**Comment by cxhernandez** [comment]
No worries! And thanks for the admin access!

Is there a lag between when things are merged here and when they show up on the omnia conda channel? I can't find it via `conda search -c omnia msmb_data`

**Comment by mpharrigan** [comment]
Everything gets sent to the "rc" release candidate label now. The idea being you test-drive the package before releasing it into the wild

`conda install -c omnia/labels/rc msmb_data`

**Comment by cxhernandez** [comment]
Ah, okay, thanks!

**Comment by mpharrigan** [comment]
Let us know when you want it in the main label

**Pull request merged**
