### PR TITLE
[ambermini] Update to 15.0.3

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
I think something weird is going on with travis building this PR.  AppVeyor passed and there doesn't appear to be a broken dependency, so merging.

**Comment by rmcgibbo** [comment]
The travis thing is more trouble than it's worth, and I don't think appveyor is actually working. It's just trying and failing to build OpenMM over and over I think.

Does ambermini require a fortran compiler?

**Comment by jchodera** [comment]
> Does ambermini require a fortran compiler?

Yes.  `gfortran`.  We have that set up on Jenkins, but I realize that this might require something to be installed for Appveyor.  Apologies for the lack of warning.

**Comment by jchodera** [comment]
> I don't think appveyor is actually working. It's just trying and failing to build OpenMM over and over I think.

If we build an OpenMM release manually just once and upload it to binstar, that would cause the appveyor script to skip trying to build OpenMM again, right?

**Comment by rmcgibbo** [comment]
Yeah. I can run through the build on my windows machine next week.

**Pull request merged**
