### PR TITLE
pyvisfile and dependencies

### PR DESCRIPTION
**Pull request by rmcgibbo**
I want to use http://mathema.tician.de/software/pyvisfile/ in a project I'm working on. Unfortunately it's a little tricky to compile all the dependencies, so I made conda packages so I don't have to do it again.

I'm not sure exactly if we've decided on the scope of this repo, but this seemed like a better place to put the recipes than anywhere else?

### CODE REVIEW

**Comment by jchodera** [comment]
Sounds reasonable!  We have a few packages like that in here too.

**Comment by rmcgibbo** [comment]
I'll test the build out on Mac before merging.

**Comment by jchodera** [comment]
This looks good to me.

**Comment by rmcgibbo** [comment]
Okay. Tested fine on os-x py27 and linux-64 py34, so I think this is good to merge.

**Pull request merged**
