### PR TITLE
[openpathsampling] 0.9.2

### PR DESCRIPTION
**Pull request by dwhswenson**
[OpenPathSampling 0.9.2](https://github.com/openpathsampling/openpathsampling/releases/tag/v0.9.2)

### CODE REVIEW

**Comment by dwhswenson** [comment]
I notice that the appveyor error is the same as in #644 and #643. The Travis error is the same as #644, but #643 passed fine. Any suggestions on how to fix? The only changes are in our `meta.yaml`: a new req, a specific pin, and a version bump. Our tests build on Travis with a local version of our package, and otherwise the same `meta.yaml`.

**Comment by jhprinz** [comment]
Seems to be a problem when importing mdtraj. Not much we can do about it. It says `glibxx` missing or so...

**Comment by jhprinz** [comment]
```
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /anaconda/conda-bld/openpathsampling_1480633113236/_t_env/lib/python2.7/site-packages/mdtraj/formats/dtr.so)
```

Is it possible that the fixing of `qt` causes a problem with the latest mdtraj?

**Comment by rmcgibbo** [comment]
This is exactly https://github.com/omnia-md/conda-recipes/issues/634#issuecomment-259250071. cc @mpharrigan

**Comment by jchodera** [comment]
Thanks, @rmcgibbo!

@dwhswenson and @jhprinz, do you need to run mdtraj at build time? If so, it looks like we have to revert to building mdtraj within omnia for the omnia version.

**Comment by jhprinz** [comment]
No, we don't need to build it. Not sure why it tries to, we just need to conda install it and then it is used in a test.

**Comment by dwhswenson** [comment]
Does the script here test that our code can be correctly imported? (`test: imports: openpathsampling` in the meta.yaml). MDTraj is imported when you run `import openpathsampling` (under a layer or two of other imports, but certainly inside of `openpathsampling.engines.openmm.tools` and `openpathsampling.collectivevariable`). Is that the problem?

**Comment by jchodera** [comment]
If you disable the `import` test, does it succeed? I don't necessarily like doing that, but it would get this built for now.

**Comment by mpharrigan** [comment]
Sorry about this. As noted above, the mdtraj conda packages are built on conda-forge which is based off of rhel/centos 6, whereas omnia uses rhel/centos 5. We could continue building two sets of binaries. If the only time this crops up is in a docker container we explicitly picked to be super old, I'd rather just say "mdtraj is centos >= 6"

**Comment by jchodera** [comment]
> We could continue building two sets of binaries

I actually think this is the best approach for now until we fully switch the build system to something that is based on CentOS 6 in preparation for migrating to conda-forge.

>  If the only time this crops up is in a docker container we explicitly picked to be super old, I'd rather just say "mdtraj is centos >= 6"

As illustrated here, that either means (1) we can't test that omnia tools that depend on `mdtraj` correctly built (which worries me a bit), or (2) you are excluding any `omnia`-built tools from using `mdtraj`. I think it may be OK to go with (1) for the very short term, though I worry this will cause trouble with quality control.

**Comment by mpharrigan** [comment]
Since the quality control is just importing the package, we could probably just do that outside the docker container.

For certain definitions of "short term" (3 months), continuing to build packages on centos 5 is a short term solution. Its EOL is March 31, 2017. We shouldn't be distributing binaries built on an unsupported OS. Does holy build box have a migration planned? Maybe this is an opportunity to start moving things to conda-forge? It would probably be worth-while to ask if you can submit a conda-forge recipe that uses the omnia openmm package (since figuring out how to build that on a new platform will be a headache).

**Comment by mpharrigan** [comment]
A very timely PR: https://github.com/phusion/holy-build-box/pull/3

**Comment by jchodera** [comment]
> For certain definitions of "short term" (3 months), continuing to build packages on centos 5 is a short term solution. Its EOL is March 31, 2017. We shouldn't be distributing binaries built on an unsupported OS.

I totally agree.

> Does holy build box have a migration planned? 

Looks like we can upgrade to the new CentOS 6 version soon, as you note.

> Maybe this is an opportunity to start moving things to conda-forge? 

I think it's great to do this, but it will be made *much* easier when `omnia` and `conda-forge` are both on CentOS6 and packages are cross-compatible during the migration.

> It would probably be worth-while to ask if you can submit a conda-forge recipe that uses the omnia openmm package (since figuring out how to build that on a new platform will be a headache).

Definitely, now that we're not just getting a `nan` sandwich with CUDA 8!

**Comment by dwhswenson** [comment]
> If you disable the `import` test, does it succeed? I don't necessarily like doing that, but it would get this built for now.

It passed Travis (Linux) when I removed the `import` test from the `meta.yaml` (waiting on OS X; [apparently it is having severe delays today](https://www.traviscistatus.com/incidents/nq0sf0srvx8s)).

Still fails AppVeyor, but I think that's a more general problem. (OPS is supposed to be skipped in the Windows tests, plus I see the same error in other PRs and in the most recent nightly.)

> Since the quality control is just importing the package, we could probably just do that outside the docker container.

Is this something I should do in this PR, or does it reflect a larger structural change in the whole of `omnia/conda-recipes`? (in which case I assume it is someone else's task)

**Comment by jchodera** [comment]
> Is this something I should do in this PR, or does it reflect a larger structural change in the whole of omnia/conda-recipes? (in which case I assume it is someone else's task)

This is a larger structural issue that needs to be addressed.

I'll look into the AppVeyor failures separately.

**Pull request merged**
