### PR TITLE
Fix gpy stuff

### PR DESCRIPTION
**Pull request by rmcgibbo**
This should fix the gpy problems from #458

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I changed back to pulling from the `devel` git branch of GPy, because python3 was broken on the latest release. But I updated the version number to 0.8.8.post1, since it's beyond 0.8.8. This PR also includes a fixed version of the Windows OpenMP compiler detection code.

**Comment by jchodera** [comment]
Wow, that's a lot of new code!

**Comment by rmcgibbo** [comment]
It looks like that, but it's not. That code is just copied from mdtraj for detecting whether we're using Visual Studio and passing the right flags.

**Comment by rmcgibbo** [comment]
(https://github.com/mdtraj/mdtraj/blob/master/basesetup.py)

**Comment by jchodera** [comment]
Looks like there is [a linux failure on travis](https://travis-ci.org/omnia-md/conda-recipes/jobs/114870980#L671-L677), but awesome work otherwise! Thanks!

**Comment by rmcgibbo** [comment]
Ready to merge

**Comment by jchodera** [comment]
Awesome, thanks!

**Pull request merged**
