### PR TITLE
Switch gaff2xml to openmoltools in yank recipe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Also increments yank to 0.6.2

### CODE REVIEW

**Comment by rmcgibbo** [comment]
do you want to remove the gaff2xml packages from binstar?

**Comment by kyleabeauchamp** [comment]
IMHO I'll leave them up for now, as they are potentially useful for reproducibility purposes.

**Comment by jchodera** [comment]
Done.

**Comment by kyleabeauchamp** [comment]
Either way.  I have no strong preference.

**Comment by jchodera** [comment]
I can regenerate packages for specific versions if we need them for paper reproducibility.

**Comment by jchodera** [comment]
Just let me know which GitHub releases are needed.  Again, sorry!

**Comment by kyleabeauchamp** [comment]
I think it's fine to just use the openmoltools version that we have, the only changes are the name change.

**Pull request merged**
