### PR TITLE
Update SCS to latest version

### PR DESCRIPTION
**Pull request by rmcgibbo**
SCS seems to have improved its build system, so none of the hacks and workarounds in the current recipe are necessary anymore.

(cc https://github.com/omnia-md/conda-recipes/pull/490#issuecomment-218936257, this fixes the numpy 1.11 SCS build on OS X)

### CODE REVIEW

**Comment by jchodera** [comment]
Is it safe to assume the `win` `py34` failures are random network errors?
```
powershell .\\devtools\\appveyor\\missing-headers.ps1
Downloading remedial  stdint.h  from http://msinttypes.googlecode.com/svn/trunk/stdint.h to C:\Program Files\Microsoft SDKs\Windows\v7.0\Include\stdint.h 
Exception calling "DownloadFile" with "2" argument(s): "The remote server 
returned an error: (404) Not Found."
At C:\projects\conda-recipes\devtools\appveyor\missing-headers.ps1:42 char:12
+            $webclient.DownloadFile($url, $filepath)
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Downloading remedial  inttypes.h  from http://msinttypes.googlecode.com/svn/trunk/inttypes.h to C:\Program Files\Microsoft SDKs\Windows\v7.0\Include\inttypes.h 
Exception calling "DownloadFile" with "2" argument(s): "The remote server 
returned an error: (404) Not Found."
At C:\projects\conda-recipes\devtools\appveyor\missing-headers.ps1:42 char:12
+            $webclient.DownloadFile($url, $filepath)
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
```

**Comment by rmcgibbo** [comment]
Those aren't network errors. They're errors because google code doesn't exist anymore.

**Comment by jchodera** [comment]
Any idea what we do about them?

**Comment by rmcgibbo** [comment]
The build failure is something different. IMO merge now and fix later though.

**Comment by mpharrigan** [comment]
I'm going to move these from `rc` to `main`

**Pull request merged**
