### PR TITLE
[ensembler] Ensembler 1.0.3 release

### PR DESCRIPTION
**Pull request by danielparton**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
this doesn't build correctly. only 1.0.2 on https://binstar.org/omnia/ensembler, and this output on jenkins:

```
======================================================================
ERROR: ensembler.tests.test_loopmodel.test_pdbfix_KC1D_HUMAN_D0_4KB8_D
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/ensembler/tests/test_loopmodel.py", line 32, in test_pdbfix_KC1D_HUMAN_D0_4KB8_D
    assert (0, 278) not in missing_residues
TypeError: argument of type 'NoneType' is not iterable
-------------------- >> begin captured logging << --------------------
info: ERROR: MPI rank 0 pdbfixer error for template KC1D_HUMAN_D0_4KB8_D - see logfile
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ensembler.tests.test_loopmodel.test_pdbfix_ABL1_HUMAN_D0_2E2B_B
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/miniconda/envs/_test/lib/python2.7/site-packages/ensembler/tests/test_loopmodel.py", line 59, in test_pdbfix_ABL1_HUMAN_D0_2E2B_B
    assert (0, 271) not in missing_residues
TypeError: argument of type 'NoneType' is not iterable
-------------------- >> begin captured logging << --------------------
info: ERROR: MPI rank 0 pdbfixer error for template ABL1_HUMAN_D0_2E2B_B - see logfile
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 28 tests in 29.282s

FAILED (errors=2)
check_lice_E> Invalid license key: XXXX
Go to http://salilab.org/modeller/ to get a license key,
and then set the 'license' variable to it in the file
/home/vagrant/miniconda/envs/_test/lib/modeller-9.15/modlib/modeller/config.py

.8-2            
    tk:               8.5.18-0         
    yaml:             0.1.6-0          
    zlib:             1.2.8-0          


Edit /home/vagrant/miniconda/envs/_test/lib/modeller-9.15/modlib/modeller/config.py
and replace XXXX with your Modeller license key
(or set the KEY_MODELLER environment variable before running 'conda install').

TESTS FAILED: ensembler-1.0.3-py27_0
```

**Comment by jchodera** [comment]
Thanks, @rmcgibbo.  I'm looking into this right now.

**Comment by jchodera** [comment]
I'm performing some direct commits to fix this.

**Comment by jchodera** [comment]
I think this is fixed now?

**Pull request merged**
