### PR TITLE
[WIP] Add numpy 1.12 builds to conda-build-all defaults

### PR DESCRIPTION
**Pull request by jchodera**
Addresses #678

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like `numpy 1.12` isn't actually available yet:
```
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 679, in create_env
    warn_on_old_conda_build(index=index)
  File "/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda/lib/python3.5/site-packages/conda_build/utils.py", line 107, in try_acquire_locks
    yield
  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 670, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 478, in install_actions
    dists_for_envs = determine_all_envs(r, specs)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 567, in determine_all_envs
    spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 567, in <genexpr>
    spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
  File "/anaconda/lib/python3.5/site-packages/conda/plan.py", line 566, in <genexpr>
    best_pkgs = (r.index[r.get_dists_for_spec(s, emptyok=False)[-1]] for s in specs)
  File "/anaconda/lib/python3.5/site-packages/conda/resolve.py", line 574, in get_dists_for_spec
    raise NoPackagesFoundError([(ms,)])
conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
  - numpy 1.12*
```
https://anaconda.org/anaconda/numpy/files

**Comment by mpharrigan** [comment]
When it becomes available from conda proper, I think we should stick to building only 1.11 and 1.12, per readme and discussion when 1.11 was released

**Comment by jchodera** [comment]
> When it becomes available from conda proper, I think we should stick to building only 1.11 and 1.12, per readme and discussion when 1.11 was released

Since the README and discussion, we've also discussed trying to sync up with conda-forge to allow migration. This should factor into our updated policy. If we diverge from conda-forge in which numpy versions we are building, we will be introducing yet more divergences that will make migration impossible.

**Comment by jchodera** [comment]
We have to wait for `anaconda` to add numpy 1.12, or for the activation of the modified conda-forge linux-anvil (#667).

**Pull request closed without merging**
