### PR TITLE
version bump 2.2.1

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
The Linux build adds an unsupported cflag...

```
gcc: error: unrecognized command line option '-fvisibility'
```

has the holy build box been upgraded?

**Comment by jchodera** [comment]
I haven't updated the omnia build box in four months:
https://hub.docker.com/r/jchodera/omnia-build-box/builds/

This build box is still being used:
https://github.com/omnia-md/conda-recipes/blob/master/.travis.yml#L19

Has something changed on the `pyemma` end?

**Comment by jchodera** [comment]
Doesn't look like it.  Maybe the `build_ext`machinery has changed?

**Comment by jchodera** [comment]
Woo!

**Comment by marscher** [comment]
The fix for conda-build just got published.

**Pull request merged**
