### PR TITLE
Release MDTraj 1.7

### PR DESCRIPTION
**Pull request by mpharrigan**
Is it just me or did the pypi urls get long?

### CODE REVIEW

**Comment by jchodera** [comment]
Your `conda-build-all` changes got sucked into this PR.

**Comment by mpharrigan** [comment]
That's by design :). Please don't merge this until we get that PR sorted out

**Comment by mpharrigan** [comment]
Rebased

**Comment by jchodera** [comment]
It did it's thing!  Packages are now up on 'rc' label:
https://anaconda.org/omnia/mdtraj/files

**Comment by mpharrigan** [comment]
The binaries are good, so I'm going to switch these to the main label. Since I have omnia permissions, I can do this myself. Others will have to request one of us to do this step

1. Go to https://anaconda.org/omnia/mdtraj/files
1. Filter by label, `rc`
1. Use checkbox to select all
1. Actions, move, `main`

**Comment by jchodera** [comment]
+1

**Pull request merged**
