### PR TITLE
gpflow

### PR DESCRIPTION
**Pull request by cxhernandez**
Add [GPFlow](https://github.com/GPflow/GPflow/) to eventually replace GPy

### CODE REVIEW

**Comment by cxhernandez** [comment]
@omnia-md/members: Is there a way to skip numpy 1.10 builds? I tried adding `np == 1.10` to the skip builds section, but it doesn't seem to be working.

**Comment by mpharrigan** [comment]
`110`
https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors

**Comment by cxhernandez** [comment]
Thanks!

**Comment by cxhernandez** [comment]
Nothing seems to be building in the Linux test 😕

**Comment by Lnaden** [comment]
I know half of what is wrong, and its a bug, but there is a fix you can do to your `meta.yaml` file to work around it (and I think you need it anyways).

1. Change your `skip: True  # [win or np == 110]` to `skip: True  # [win]`
1. Add the following to your file in the `requirements` section: 
  ```
  run:
    - python
    - scipy
    - numpy >1.10
    - pandas
    - tensorflow
``` 
  * This is missing so your file is saying it does not need these things to run, only to build. The build would be deployed and people could then install this package without python technically.
3. Change the `numpy` in the `build` section to be the same as the run section I showed.

This will require people have numpy > 1.10 if they want to use your package. Now if you want people to specify which numpy they use, you would need `numpy x.x`, and then I would also have to fix the `conda-build-all` script for a few bugs to get that to work right again.

`conda-build` and the `meta.yaml` format has changed so much from when our build script was written, things like this crop up. We are trying to move to the `conda-forge` framework partially so we dont have to maintain our own version of this script. If you need the `numpy x.x` function, I will need to spend some time fixing the script, but I don't know when I will have the time to devote to that in the near future right now.

**Comment by mpharrigan** [comment]
does gpflow compile against the numpy api?

**Comment by cxhernandez** [comment]
> does gpflow compile against the numpy api?

No but it's a tensorflow requirement, which currently only works with numpy >1.10

**Comment by cxhernandez** [comment]
Thanks @Lnaden! Try that now

**Comment by mpharrigan** [comment]
skipping numpy builds only makes sense if you're compiling different packages for different numpy abi's (as @Lnaden has pointed out)

**Comment by cxhernandez** [comment]
Actually nvm:

```
install_requires=['numpy>=1.9', 'scipy>=0.16', 'pandas>=0.18.1'],
```

Looks like it [does](https://github.com/GPflow/GPflow/blob/master/setup.py#L49)

**Comment by Lnaden** [comment]
The requirements in the `setup.py` file are roughly equivalent to the conda `meta.yaml` requirements' `run` section if I understand them right. So long as you don't really have a conflict, it should build as I put it

**Comment by cxhernandez** [comment]
Ahah! That seems to have gotten the builds started. Now for a new issue:

```
ImportError: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /anaconda/conda-bld/gpflow_1493845345443/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)
Failed to load the native TensorFlow runtime.
```

**Comment by Lnaden** [comment]
One other thing, there is no osx tensorflow on the anaconda default channel, so these builds will not work on OSX.

**Comment by mpharrigan** [comment]
Looks like tensorflow needs centos > 5. @Lnaden has the omnia migration to centos 6 ready but we're waiting to build an openmm patch release before it's merged.

**Comment by cxhernandez** [comment]
Cool! Seems like Linux builds just fine now 😄

**Comment by Lnaden** [comment]
This will have to wait until we can merge in the conda-forge PR.

**Comment by cxhernandez** [comment]
That's fine. I just wanted to be sure it would work, since this will be the dependency for something currently in development.

**Pull request merged**
