### PR TITLE
version bump pyemma 2.0.2

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
We won't need 2.0.2 / the bhmm upgrade for the workshop, so no need to 
hurry on this one.

Am 23/10/15 um 19:00 schrieb Martin K. Scherer:
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/omnia-md/conda-recipes/pull/363
>
>
>         Commit Summary
>
>   * version bump pyemma 2.0.2
>
>
>         File Changes
>
>   * *M* pyemma/meta.yaml
>     <https://github.com/omnia-md/conda-recipes/pull/363/files#diff-0>
>     (10)
>
>
>         Patch Links:
>
>   * https://github.com/omnia-md/conda-recipes/pull/363.patch
>   * https://github.com/omnia-md/conda-recipes/pull/363.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/363>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Sorry, I'll close this because I prefer to run the workshop with 2.0.1, especially if there is a change in the featurizer that would break our notebooks. Let's look over this again and do the release next Monday.

**Comment by jchodera** [comment]
If there are API changes that would break backwards compatibility, shouldn't this be a major version number increment rather than a minor or bugfix version increment?

**Comment by franknoe** [comment]
This is why I had stopped this release. We can do the change without 
breaking the API.

Am 24/10/15 um 15:29 schrieb John Chodera:
>
> If there are API changes that would break backwards compatibility, 
> shouldn't this be a major version number increment rather than a minor 
> or bugfix version increment?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/363#issuecomment-150811849>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jchodera** [comment]
Good call!

**Comment by marscher** [comment]
I actually do not understand why this api changing PR has been merged anyway.

**Comment by franknoe** [comment]
I don't recall. Anyway, let's just keep topfile and add top or topology (what is used in mdtraj?) in order to add the option to use a non-file topology object.

**Comment by marscher** [comment]
The keyword is "top" in mdtraj, it is a trivial change to add this. However the recall of the recall can not be recalled, because I've deleted the git tags already :+1: (the tag might still reside in some of git(-hubs) backup system, but thats not feasible nor time efficient to restore it).

Let's just do this on Monday.
Have a nice weekend,
Best

**Comment by franknoe** [comment]
No problem. Yep, tomorrow.

Am 25/10/15 um 02:36 schrieb Martin K. Scherer:
>
> The keyword is "top" in mdtraj, it is a trivial change to add this. 
> However the recall of the recall can not be recalled, because I've 
> deleted the git tags already :+1: (the tag might still reside in some 
> of git(-hubs) backup system, but thats not feasible nor time efficient 
> to restore it).
>
> Let's just do this on Monday.
> Have a nice weekend,
> Best
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/363#issuecomment-150876343>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request closed without merging**
