### PR TITLE
[progressbar] Add progressbar from conda/conda-recipes

### PR DESCRIPTION
**Pull request by jchodera**
From https://github.com/conda/conda-recipes/tree/master/progressbar, since somehow that package is no longer be maintained in the main anaconda channel.

### CODE REVIEW

**Comment by jchodera** [comment]
Ah. This may be because `progressbar` is not yet py3.x ready:
```
+ /Users/travis/anaconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import progressbar
  File "/Users/travis/anaconda/conda-bld/work/progressbar-2.3/progressbar/__init__.py", line 59, in <module>
    from progressbar.widgets import *
  File "/Users/travis/anaconda/conda-bld/work/progressbar-2.3/progressbar/widgets.py", line 121, in <module>
    class FileTransferSpeed(Widget):
  File "/Users/travis/anaconda/envs/_build/lib/python3.4/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
ValueError: 'format' in __slots__ conflicts with class variable
Command failed: /bin/bash -x -e /Users/travis/build/omnia-md/conda-recipes/progressbar/build.sh
Removing old build environment
Removing old work directory
```

**Comment by rmcgibbo** [comment]
Can you add a `skip` entry then?

**Comment by jchodera** [comment]
Can we just unmerge?

**Comment by swails** [comment]
> Can we just unmerge?

:).  Why not just revert?  That's easy to do from `gitk`

**Comment by bas-rustenburg** [comment]
@jchodera: Is progressbar2 py3.x ready? You could consider switching to that. http://progressbar-2.readthedocs.org/en/latest/

**Pull request merged**
