### PR TITLE
Added jinja2 to appveyor

### PR DESCRIPTION
**Pull request by jchodera**
Should fix complaints about missing `jinja2`.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
no don't do this.

**Comment by jchodera** [comment]
Why?  Half the output is complaints that `jinja2` isn't installed.

**Comment by jchodera** [comment]
```
 
Executing: python conda-build-all --check-against omnia --upload omnia --python 34 --numpy 19 *
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support 
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
Removing old build environment
Removing old work directory
BUILD START: python-coveralls-2.5.0-py34_0
Fetching package metadata: ........ 
```

**Comment by rmcgibbo** [comment]
jinja2 being present triggers a bug in conda-build: https://github.com/conda/conda-build/pull/520

**Comment by rmcgibbo** [comment]
all of this issue is solved by not installing jinja2: https://github.com/omnia-md/conda-recipes/issues/277. it will be fixed when there's a new release of conda-build because I fixed the underlying bug upstream.

**Comment by jchodera** [comment]
Le sigh.

**Comment by jchodera** [comment]
Thanks for fixing the upstream bug!

**Pull request closed without merging**
