### PR TITLE
Release msmbuilder 3.5

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
why is this trying to build everything

**Comment by mpharrigan** [comment]
@jchodera @marscher any ideas?

**Comment by mpharrigan** [comment]
Rebased

**Comment by jchodera** [comment]
Sorry for being out of the loop! Was at grant reviews.

**Comment by mpharrigan** [comment]
Rebased again to trigger new build

**Pull request merged**
