### PR TITLE
Added mpi4py and pyyaml to requirements for yank.

### PR DESCRIPTION
**Pull request by jchodera**
I've added `mpi4py` (necessary if MPI runs are desired) and `pyyaml` (since we'll need it soon anyway).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Should we add these requirements in the devtools version as well?  It's probably good to avoid getting out of sync

**Comment by kyleabeauchamp** [comment]
Do we need mpi4py in the build section or just run?

**Comment by jchodera** [comment]
Done.

**Comment by jchodera** [comment]
Whoops, forgot to increment the build number for the `yank` recipe too.  Will do in a separate PR.

**Pull request merged**
