### PR TITLE
Add recipe for saltswap v0.5.1

### PR DESCRIPTION
**Pull request by bas-rustenburg**
This PR adds a conda recipe for the saltswap package by @gregoryross.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
Looks like for the time being, saltswap isn't windows compatible.

**Comment by Lnaden** [comment]
Not quite, OpenMM is missing for Python 2.7 windows ( i think there was an issue for this), and is simply not built on 32 bit arch for windows. It does build for Py3k and 64bit.

**Comment by bas-rustenburg** [comment]
Ah, good call. Do you know the syntax/have an example to restrict the builds to 64bit/py3?

**Comment by Lnaden** [comment]
Half-ly?

```
build:
    skip: True # [py2k]
```
will skip the python 2 builds, but I'm not sure about the architecture, it may be something like:

```
build:
    skip: True # [(py2k and win) or win32]
```
Unfortunately, the conda docs are real light on valid skip strings, the best I could find for this is here:
https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors

but I also found some other things here which may help, but is not quite what you need.
https://github.com/conda/conda-build/pull/1753

**Pull request merged**
