### PR TITLE
Update dockerfile to update yum repository

### PR DESCRIPTION
**Pull request by jlmaccal**
This adds commands to update the yum repository to point to the correct new location and installs `groff`, which is needed for `awscli`.

@jchodera or @lnaden, can you trigger a new build of the docker image?

### CODE REVIEW

**Comment by jchodera** [comment]
No, that's the wrong Dockerfile!

@Lnaden can add them to the new `omnia-linux-anvil` if you just let him know what you need.

@Lnaden : We should also remove the deprecated dockerfile in `devtools/` so it doesn't cause confusion.

**Comment by jchodera** [comment]
Sorry about this, @jlmaccal. @Lnaden *is* actively working on this---he spent all day working on the update.

**Comment by jlmaccal** [comment]
Oops.. in that case only
```
RUN yum install -y groff
```
is the only necessary addition. The repository changes were only necessary for CentOS5.

**Comment by Lnaden** [comment]
>  We should also remove the deprecated dockerfile in 

Yup, already part of the PR.

@jlmaccal The docker file we will be switching to is at [this repo](https://github.com/omnia-md/omnia-linux-anvil) which auto-rebuilds the docker image that the new builds will use. I'll take care of this first thing in the morning and for now will re-open this ticket/PR to serve as a reminder to myself.

**Pull request closed without merging**
