### PR TITLE
Arpack

### PR DESCRIPTION
**Pull request by rmcgibbo**
@hainm, this builds arpack for OS X and linux without requiring linking against *any* fortran libraries (no libgfortran or libquadmath).

### CODE REVIEW

**Comment by hainm** [comment]
Awesome. I will try. Thanks. Ping @drroe here too.

**Comment by hainm** [comment]
@rmcgibbo I clone your f2c and arpack folders and try to `conda build arpack`, got errors. Any idea why?

```
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cnaitr.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cgetv0.f)'
F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsconv.f)
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cneigh.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cngets.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cnapps.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cnaup2.f)'
make: *** [SRC/cgetv0.c] Error 2
make: *** Waiting for unfinished jobs....
make: *** [SRC/cnaitr.c] Error 2
make: *** [SRC/cneigh.c] Error 2
make: *** [SRC/cngets.c] Error 2
make: *** [SRC/cnapps.c] Error 2
make: *** [SRC/cnaup2.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cstatn.f)'
make: *** [SRC/cstatn.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dlaqrb.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 csortc.f)'
make: *** [SRC/dlaqrb.c] Error 2
make: *** [SRC/csortc.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cnaupd.f)'
make: *** [SRC/cnaupd.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dnaitr.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 cneupd.f)'
make: *** [SRC/dnaitr.c] Error 2
make: *** [SRC/cneupd.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dgetv0.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
make: *** [SRC/dgetv0.c] Error 2
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dlahqr2.f)'
make: *** [SRC/dlahqr2.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dnaup2.f)'
make: *** [SRC/dnaup2.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dneupd.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
make: *** [SRC/dneupd.c] Error 2
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dnaupd.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dngets.f)'
make: *** [SRC/dnaupd.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsapps.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dnapps.f)'
make: *** [SRC/dngets.c] Error 2
make: *** [SRC/dsapps.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsaupd.f)'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dnconv.f)'
make: *** [SRC/dnapps.c] Error 2
make: *** [SRC/dsaupd.c] Error 2
make: *** [SRC/dnconv.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dneigh.f)'
make: *** [SRC/dneigh.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsaup2.f)'
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
make: /bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsaitr.f)'
*** [SRC/dsaup2.c] Error 2
make: *** [SRC/dsaitr.c] Error 2
/bin/sh: -c: line 0: syntax error near unexpected token `cd'
/bin/sh: -c: line 0: `F_SRC(cd SRC/ && f2c -ARw8 -Nn802 -Nq300 -Nx400 dsconv.f)'
make: *** [SRC/dsconv.c] Error 2
Command failed: /bin/bash -x -e /u1/haichit/amber_conda/conda-recipes/argpack/build.sh
```

**Comment by hainm** [comment]
never mind: I missed `#!/bin/bash`

**Comment by rmcgibbo** [comment]
(did you not just `git`? e.g `git pull https://github.com/rmcgibbo/conda-recipes.git f2c` to pull this branch, doesn't require copy-pasting anything).

**Comment by hainm** [comment]
:D I open your PR and though it's faster to copy and paste. (But I am wrong since arpack build need f2c).

**Comment by rmcgibbo** [comment]
It should actually be possible to do this without f2c using the same static libgfortran trick from https://github.com/omnia-md/conda-recipes/pull/345#issue-110837185

**Comment by rmcgibbo** [comment]
nvm. there's a conda libgcc that just provides the necessary shared libraries (libgfortran, etc), so that's a better solution.

**Pull request closed without merging**
