### PR TITLE
[openmm] 7.0rc1 build 1

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
@peastman : Hopefully fixed!

**Comment by peastman** [comment]
Great!

**Comment by mpharrigan** [comment]
I don't think `git_url` and `git_rev` are appropriate here. It's still a zipfile, albeit one served by github

**Comment by jchodera** [comment]
Whoops!  Thanks for catching that.  Not sure how that happened.

**Pull request merged**
