### PR TITLE
pyemma v2.1.2

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
I don't think we want to release anything before resolving #782. Also #764 is not yet fixed.

**Comment by marscher** [comment]
Well, we introduced a memory leak in the last version, which in my honest opinion legitimate a micro release.

**Comment by franknoe** [comment]
Please see #782 - no releases before proper testing. Notebooks are failing with this version.

**Comment by franknoe** [comment]
ok, let's do this:

1. check+merge #783
2. solve #764
3. update IPython notebook output on pyemma.org
4. if all looks OK, release.

**Pull request closed without merging**
