### PR TITLE
[openmm] OpenMM 6.3

### PR DESCRIPTION
**Pull request by rmcgibbo**
I would prefer to get this right the first time, so no merge yet.

### CODE REVIEW

**Comment by swails** [comment]
+1.  When will these be posted?  After this gets merged, or shortly thereafter?

**Comment by rmcgibbo** [comment]
This works for Linux and OSX, so it can probably be merged. Still needs some work for Win-64 I think, but we can do that later.

**Comment by jchodera** [comment]
Thanks!  I'm still debugging some issues with Jenkins failing all of a sudden, so give me a few more min before we merge.

**Comment by jchodera** [comment]
See #270

**Comment by jchodera** [comment]
OK, I think we're sorted now.

**Comment by jchodera** [comment]
Merging #269 first just to double-check everything works as intended.

**Comment by jchodera** [comment]
Any chance you could retrigger the appveyor build for this PR?  I wonder if #271 fixed your issues.

**Pull request merged**
