### PR TITLE
Updated BHMM recipe for 0.2.0

### PR DESCRIPTION
**Pull request by jchodera**
The tests are failing; not ready to merge.

### CODE REVIEW

**Comment by jchodera** [comment]
This should be ready to go if all tests pass.

**Comment by jchodera** [comment]
Looks like there is an issue with the `behave` recipe for python 3.x that seems unrelated to this PR:
https://travis-ci.org/omnia-md/conda-recipes/builds/61404833#L2490-L2511
```
BUILD START: behave-1.2.5-py33_0
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[4/6                 ]|##################################                 |  66%
Hint: the following packages conflict with each other:
  - python 3.3*
  - parse_type >=0.3.4
Removing old build directory
Removing old work directory
BUILD START: behave-1.2.5-py34_0
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[3/5                 ]|##############################                     |  60%
Hint: the following packages conflict with each other:
  - python 3.4*
  - parse_type >=0.3.4
Removing old build directory
Removing old work directory
```

**Comment by jchodera** [comment]
There are indeed some `bhmm` and `pyemma` related errors, though, suggesting a conflict between `scipy >= 0.15` and `mdtraj`:
https://travis-ci.org/omnia-md/conda-recipes/builds/61404833#L4011-L4037

**Comment by jchodera** [comment]
@marscher and @franknoe: Do `pyemma` and `bhmm` really require `scipy >= 0.15`?  It appears that only [`scipy 0.14`](https://binstar.org/search?q=scipy) is prevalent on binstar.  We may have to create a recipe and build our own `scipy 0.15` if this is really necessary.

**Comment by franknoe** [comment]
bhmm certainly not. pyemma - not for any of the features I can think of, 
but I think the person to ask here is @trendelkampschroer

Am 06/05/15 um 06:07 schrieb John Chodera:
>
> @marscher <https://github.com/marscher> and @franknoe 
> <https://github.com/franknoe>: Do |pyemma| and |bhmm| really require 
> |scipy >= 0.15|? It appears that only |scipy 0.14| 
> <https://binstar.org/search?q=scipy> is prevalent on binstar. We may 
> have to create a recipe and build our own |scipy 0.15| if this is 
> really necessary.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99315362>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by trendelkampschroer** [comment]
Hallo Frank,

fuer Emma sind die Vorraussetzungen, scipy>=0.11. Vielleicht braucht
mdtraj oder scikit-learn eine neuere scipy Version?

pyemma benutzt nur features die es in scipy>=0.11  gibt, 0.14 sollte
also vollkommen ausreichen.


On 06.05.2015 08:09, Frank Noe wrote:
> bhmm certainly not. pyemma - not for any of the features I can think of,
> but I think the person to ask here is @trendelkampschroer
>
> Am 06/05/15 um 06:07 schrieb John Chodera:
> >
> > @marscher <https://github.com/marscher> and @franknoe
> > <https://github.com/franknoe>: Do |pyemma| and |bhmm| really require
> > |scipy >= 0.15|? It appears that only |scipy 0.14|
> > <https://binstar.org/search?q=scipy> is prevalent on binstar. We may
> > have to create a recipe and build our own |scipy 0.15| if this is
> > really necessary.
> >
> > —
> > Reply to this email directly or view it on GitHub
> >
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99315362>.
> >
>
>
> -- 
>
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
>
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99336486>.
>

-- 
Benjamin Trendelkamp-Schroer
Fritschestrasse 24
10585 Berlin

**Comment by franknoe** [comment]
Thanks Ben. John: pyEMMA only needs scipy >= 0.11, so we should not have 
a problem there. We're not sure if mdtraj or sklearn have higher 
requirements. Our dependency on sklearn is only temporary and will be 
removed in the next version.

John where did you get the 0.15 from? In the pyEMMA setup.py we have 
scipy >= 0.11, in the bhmm setup.py the version number is not specified. 
Maybe there is an inconsistent dependency statement in one of the conda 
recipies?

Am 06/05/15 um 09:57 schrieb Benjamin Trendelkamp-Schroer:
> Hallo Frank,
>
> fuer Emma sind die Vorraussetzungen, scipy>=0.11. Vielleicht braucht
> mdtraj oder scikit-learn eine neuere scipy Version?
>
> pyemma benutzt nur features die es in scipy>=0.11 gibt, 0.14 sollte
> also vollkommen ausreichen.
>
>
> On 06.05.2015 08:09, Frank Noe wrote:
> > bhmm certainly not. pyemma - not for any of the features I can think of,
> > but I think the person to ask here is @trendelkampschroer
> >
> > Am 06/05/15 um 06:07 schrieb John Chodera:
> > >
> > > @marscher <https://github.com/marscher> and @franknoe
> > > <https://github.com/franknoe>: Do |pyemma| and |bhmm| really require
> > > |scipy >= 0.15|? It appears that only |scipy 0.14|
> > > <https://binstar.org/search?q=scipy> is prevalent on binstar. We may
> > > have to create a recipe and build our own |scipy 0.15| if this is
> > > really necessary.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99315362>.
> > >
> >
> >
> > --
> >
> > ----------------------------------------------
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> >
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > Mail: Arnimallee 6, 14195 Berlin, Germany
> > ----------------------------------------------
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99336486>.
> >
>
> -- 
> Benjamin Trendelkamp-Schroer
> Fritschestrasse 24
> 10585 Berlin
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99364080>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
There is definitely a scipy>=0.15 in Anaconda, but it is only built for 
latest NumPy 1.9. Why do we need to support all these old NumPys out 
there? It would only make sense if we would be packaging for Debian 
stable or something (stable is now also using 1.8). Installing an 
updated NumPy with conda is a no brainer.

**Comment by franknoe** [comment]
I don't understand this reply. We weren't talking about numpys.

John's question was whether bhmm and/or pyemma require scipy >= 0.15. I 
believe none of them do, and as far as I can see there is no such 
requirement stated in the setup.py scripts. Neither it is in bhmm's 
conda recipe. I don't have a conda recipe for pyemma, or don't know 
where that is (there is no devtools/conda-recipe/ in the pyemma repo).

So unless anyone else knows, I think John needs to tell us where he saw 
the 0.15 requirement.

Am 06/05/15 um 13:01 schrieb Martin K. Scherer:
> There is definitely a scipy>=0.15 in Anaconda, but it is only built for
> latest NumPy 1.9. Why do we need to support all these old NumPys out
> there? It would only make sense if we would be packaging for Debian
> stable or something (stable is now also using 1.8). Installing an
> updated NumPy with conda is a no brainer.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99418163>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Pyemma has declared this dependency. We can update the recipe in the
omnia-recipes repo and trigger a new build number. Nevertheless I vote
for using recent versions, since I do not expect the Anaconda people to
backport bug fixes.

**Comment by franknoe** [comment]
I see. Well I don't have a strong feeling about requiring a new version 
when an old one is sufficient, but I believe we should be consistent 
between requirements in different setups. In setup.py scipy >= 0.11 is 
required, so it's weird to require scipy >= 0.15 in conda.

Am 06/05/15 um 14:55 schrieb Martin K. Scherer:
> Pyemma has declared this dependency. We can update the recipe in the
> omnia-recipes repo and trigger a new build number. Nevertheless I vote
> for using recent versions, since I do not expect the Anaconda people to
> backport bug fixes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99442333>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
BTW: Even if we request >= 0.11, wouldn't that automatically install the 
newest
available version (e.g. 0.14)?
I thought specifying version numbers was in order to define minimum 
requirements
for the code to run, rather than expressing a preference to have the 
latest version of everything.

Am 06/05/15 um 14:55 schrieb Martin K. Scherer:
> Pyemma has declared this dependency. We can update the recipe in the
> omnia-recipes repo and trigger a new build number. Nevertheless I vote
> for using recent versions, since I do not expect the Anaconda people to
> backport bug fixes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99442333>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by trendelkampschroer** [comment]
I think that is correct. scipy>=0.11 specifies the minimum requirement, but easy_install/pip is free to install any later version also.

**Comment by marscher** [comment]
alright. Will update the recipe.

**Comment by franknoe** [comment]
OK, thanks

Am 06/05/15 um 15:31 schrieb Martin K. Scherer:
> alright. Will update the recipe.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99460097>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by trendelkampschroer** [comment]
If however the conda-build for scipy-0.11 has a bug which is only fixed for scipy>=0.12 then it makes sense to have different requirements for pip/easy_install vs conda. 

I am not sure if that is the case for scipy-0.11, though.

**Comment by franknoe** [comment]
I am not aware that we had a scipy issue.

Am 06/05/15 um 15:35 schrieb Benjamin Trendelkamp-Schroer:
>
> If however the conda-build for scipy-0.11 has a bug which is only 
> fixed for scipy>=0.12 then it makes sense to have different 
> requirements for pip/easy_install vs conda.
>
> I am not sure if that is the case for scipy-0.11, though.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99461782>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
At least for conda we are not able to use scipy 0.11 anymore, since this
would depend on numpy-1.7, which is not supported by mdtraj anymore
(they simply do not provide binaries built against np-1.7). I do not
know if source building mdtraj (pypi) supports old numpy versions.

Actually supporting all these old version combinations will enforce us
to also test this. I guess thats why I just enforced using a recent
version, which I have tested for the last update of the recipe.

We can integrate this in our new CI service as soon as we get it, if
desired.

**Comment by franknoe** [comment]
I would see a problem if we specificy exact versions, but why is there a 
problem with specifying minimal requirements.
If we require scipy >= 0.11 and mdtraj, but mdtraj requires scipy >= 
0.12 for some reason, then a conda install pyemma would automatically 
trigger a scipy install >= 0.12, or not?

Am 06/05/15 um 15:42 schrieb Martin K. Scherer:
> At least for conda we are not able to use scipy 0.11 anymore, since this
> would depend on numpy-1.7, which is not supported by mdtraj anymore
> (they simply do not provide binaries built against np-1.7). I do not
> know if source building mdtraj (pypi) supports old numpy versions.
>
> Actually supporting all these old version combinations will enforce us
> to also test this. I guess thats why I just enforced using a recent
> version, which I have tested for the last update of the recipe.
>
> We can integrate this in our new CI service as soon as we get it, if
> desired.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99464153>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 06.05.2015 um 15:47 schrieb Frank Noe:
> I would see a problem if we specificy exact versions, but why is there a
> problem with specifying minimal requirements.
> If we require scipy >= 0.11 and mdtraj, but mdtraj requires scipy >=
> 0.12 for some reason, then a conda install pyemma would automatically
> trigger a scipy install >= 0.12, or not?
It will.

But if we know we need at least scipy>=0.14 because of other
dependencies, why shouldn't we declare. Does it not cause even more
confusion?

**Comment by franknoe** [comment]
I see, you are saying that mdtraj requires >=0.14, so we should require 
 >=0.14 too.

I am not sure what the usual policy is in this case. My feeling is that 
we should only define the minimal requirements based on the 
functionalities we use in our package. Any of the packages we depend 
upon could in a later version change their dependencies, and it seems to 
be the job of an installation system to figure out which versions should 
finally be installed given the entire dependency tree, rather than doing 
this work manually.

Am 06/05/15 um 15:54 schrieb Martin K. Scherer:
> Am 06.05.2015 um 15:47 schrieb Frank Noe:
> > I would see a problem if we specificy exact versions, but why is there a
> > problem with specifying minimal requirements.
> > If we require scipy >= 0.11 and mdtraj, but mdtraj requires scipy >=
> > 0.12 for some reason, then a conda install pyemma would automatically
> > trigger a scipy install >= 0.12, or not?
> It will.
>
> But if we know we need at least scipy>=0.14 because of other
> dependencies, why shouldn't we declare. Does it not cause even more
> confusion?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99471316>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
We are already using numpy-1.8 features. Since in conda scipy and numpy
are built as pairs (eg. numpy-1.6 with scipy-0.11), we are already
minimum depending on scipy-0.14 (dep of np18).

Building from source does not enforce this pair relationship, since it
is principle possible to mix arbitray numpy with scipy versions. That is
why we have different versions in conda recipe and setup.py

I've discussed this with Ben and we have agreed we should declare it
like this.

**Comment by franknoe** [comment]
Well if that is so we clearly have >= 0.14 as a requirement.

Am 06/05/15 um 16:34 schrieb Martin K. Scherer:
> We are already using numpy-1.8 features. Since in conda scipy and numpy
> are built as pairs (eg. numpy-1.6 with scipy-0.11), we are already
> minimum depending on scipy-0.14 (dep of np18).
>
> Building from source does not enforce this pair relationship, since it
> is principle possible to mix arbitray numpy with scipy versions. That is
> why we have different versions in conda recipe and setup.py
>
> I've discussed this with Ben and we have agreed we should declare it
> like this.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99493044>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 06.05.2015 um 16:35 schrieb Frank Noe:
> Well if that is so we clearly have >= 0.14 as a requirement.
In conda, yes.

**Comment by franknoe** [comment]
Why only in conda? Shouldn't pip have the same dependency?

Am 06/05/15 um 16:36 schrieb Martin K. Scherer:
> Am 06.05.2015 um 16:35 schrieb Frank Noe:
> > Well if that is so we clearly have >= 0.14 as a requirement.
> In conda, yes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99493712>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jchodera** [comment]
The problem is a little different.

I believe mdtraj just requires scipy. No version is specified.

Binstar has a scipy 0.14 package available but not 0.15.  If we need 0.15 we will have to package it or ourselves.

Our policy needs to be that we specify only the minimum working version in order to maximize the potential for multiple packages working together.  If all versions work, we don't need to specify a version restriction at all.

Back to the original question: Does pyemma or BHMM use some features only found in scipy 0.15, or can I eliminate that restriction?

**Comment by jchodera** [comment]
Oh!  I missed most of this thread.  Reading now...

**Comment by jchodera** [comment]
> I believe we should be consistent 
> between requirements in different setups. In setup.py scipy >= 0.11 is 
> required, so it's weird to require scipy >= 0.15 in conda.

We definitely have to keep setup.py requirements and conda requirements consistent!  I will submit a PR to update these in a bit.

**Comment by jchodera** [comment]
We don't need to worry about dependencies for other packages like mdtraj.  We should only specify the minimal requirements for the package we are building.

**Comment by marscher** [comment]
Am 06.05.2015 um 16:42 schrieb John Chodera:
> The problem is a little different.
> 
> I believe mdtraj just requires scipy. No version is specified.
> 
> Binstar has a scipy 0.14 package available but not 0.15. If we need 0.15
> we will have to package it or ourselves.
That is not true. See the output of

    conda search scipy |grep 0.15

> 
> Our policy needs to be that we specify only the minimum working version
> in order to maximize the potential for multiple packages working
> together. If all versions work, we don't need to specify a version
> restriction at all.
I agree. That is a good policy.
> 
> Back to the original question: Does pyemma or BHMM use some features
> only found in scipy 0.15, or can I eliminate that restriction?
No. We only need at least np18

**Comment by franknoe** [comment]
In the last comment you said numpy 1.8 and scipy 0.14 are a match. So if 
numpy >= 1.8 is a requirement we should go for scipy >=0.14.
We do certainly not use features of scipy 0.15.

So I believe in both conda and setup.py our requirements should read
numpy >= 1.8
scipy >= 0.14

Any disagreement?


Am 06/05/15 um 16:45 schrieb Martin K. Scherer:
> Am 06.05.2015 um 16:42 schrieb John Chodera:
> > The problem is a little different.
> >
> > I believe mdtraj just requires scipy. No version is specified.
> >
> > Binstar has a scipy 0.14 package available but not 0.15. If we need 0.15
> > we will have to package it or ourselves.
> That is not true. See the output of
>
> conda search scipy |grep 0.15
>
> >
> > Our policy needs to be that we specify only the minimum working version
> > in order to maximize the potential for multiple packages working
> > together. If all versions work, we don't need to specify a version
> > restriction at all.
> I agree. That is a good policy.
> >
> > Back to the original question: Does pyemma or BHMM use some features
> > only found in scipy 0.15, or can I eliminate that restriction?
> No. We only need at least np18
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99496873>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
yes. Will prepare a PR with scipy>=0.14 and np>=1.8

**Comment by jchodera** [comment]
> > Binstar has a scipy 0.14 package available but not 0.15. If we need 0.15
> > we will have to package it or ourselves.
> That is not true. See the output of
> 
> conda search scipy |grep 0.15

Do you have other channels besides Omnia added?  When looking through binstar, I though I only saw 0.14 on the default channels.

> No. We only need at least np18

Is the numpy 18 dependency due to an actual numpy 18 only feature, or due to a dependency that only uses 18?

**Comment by jchodera** [comment]
> In the last comment you said numpy 1.8 and scipy 0.14 are a match. So if 
> numpy >= 1.8 is a requirement we should go for scipy >=0.14.
> We do certainly not use features of scipy 0.15.
> 
> So I believe in both conda and setup.py our requirements should read
> numpy >= 1.8
> scipy >= 0.14
> 
> Any disagreement?

The point of conda's automatic dependency resolution is that we should not have to figure out which versions "match" by ourselves.  We should only have to specify the minimum allowable versions for direct dependencies.  The constraint does the rest (though there is a bit of magic in the packaging process that tries to build all allowable versions of packages).

**Comment by jchodera** [comment]
> yes. Will prepare a PR with scipy>=0.14 and np>=1.8

We should NOT do this unless we directly use features that only appear in these specific versions but not earlier versions.

**Comment by franknoe** [comment]
We do use numpy features of 1.8 and scipy features of 0.11 in pyemma. So 
you are saying we should only use
     numpy >= 1.8
     scipy >= 0.11
Is that correct?




Am 06/05/15 um 16:58 schrieb John Chodera:
> > In the last comment you said numpy 1.8 and scipy 0.14 are a match. 
> So if
> > numpy >= 1.8 is a requirement we should go for scipy >=0.14.
> > We do certainly not use features of scipy 0.15.
> >
> > So I believe in both conda and setup.py our requirements should read
> > numpy >= 1.8
> > scipy >= 0.14
> >
> > Any disagreement?
>
> The point of conda's automatic dependency resolution is that we should 
> not have to figure out which versions "match" by ourselves. We should 
> only have to specify the minimum allowable versions for direct 
> dependencies. The constraint does the rest (though there is a bit of 
> magic in the packaging process that tries to build all allowable 
> versions of packages).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99502552>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 06.05.2015 um 17:01 schrieb Frank Noe:
> We do use numpy features of 1.8 and scipy features of 0.11 in pyemma. So
> you are saying we should only use
> numpy >= 1.8
> scipy >= 0.11
> Is that correct?
Yes. And conda will pull in at least scipy-0.14

We can also remove the minimum requirement of scipy and let conda handle it.

**Comment by jchodera** [comment]
> We do use numpy features of 1.8 and scipy features of 0.11 in pyemma. So 
> you are saying we should only use
> numpy >= 1.8
> scipy >= 0.11
> Is that correct?

Yes!  And if we don't use these special features in BHMM, we don't specify version numbers. 

The constraint solver will sort out compatible versions for us.

If we fail to do this and instead specify vet restrictive version numbers, we can cause lots of incompatibilities between packages unnecessarily

**Comment by franknoe** [comment]
I agree with John. And we should request both numbers explicitly because 
we do use features of scipy 0.11, even if we know that numpy 1.8 will 
actually pull a newer version - simply because it seem conceptually the 
right thing to decide requirements of a package based on a local 
perspective.

Am 06/05/15 um 17:05 schrieb John Chodera:
> > We do use numpy features of 1.8 and scipy features of 0.11 in 
> pyemma. So
> > you are saying we should only use
> > numpy >= 1.8
> > scipy >= 0.11
> > Is that correct?
>
> Yes! And if we don't use these special features in BHMM, we don't 
> specify version numbers.
>
> The constraint solver will sort out compatible versions for us.
>
> If we fail to do this and instead specify vet restrictive version 
> numbers, we can cause lots of incompatibilities between packages 
> unnecessarily
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99505018>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
right. the bhmm package should not specify any minimum requirements, if
it is compatible with the old stuff (which I assume is untested, isn't it?)

**Comment by franknoe** [comment]
I believe in bhmm it should be

numpy >= 1.7 (e.g. numpy.random.choice)
scipy >= 0.11 (used in the msm package, although that will at some point 
no longer be needed when pyEMMA has the new reversible transition matrix 
sampler activated)

Am 06/05/15 um 17:08 schrieb Martin K. Scherer:
> right. the bhmm package should not specify any minimum requirements, if
> it is compatible with the old stuff (which I assume is untested, isn't 
> it?)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99505842>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jchodera** [comment]
>
> I believe in bhmm it should be
>
> numpy >= 1.7 (e.g. numpy.random.choice)
> scipy >= 0.11 (used in the msm package, although that will at some point
> no longer be needed when pyEMMA has the new reversible transition matrix
> sampler activated)
>

Sounds great.  How about @marscher fixes the conda recipes for `pyemma` and
I'll handle the updates for `bhmm`?

Again, we're just stating the minimum required versions of direct
dependencies.  The constraint solver will do the rest.

**Comment by marscher** [comment]
Ok. I'll send in a PR for omnia-recipes

**Comment by franknoe** [comment]
OK thanks

Am 06/05/15 um 17:34 schrieb John Chodera:
> >
> > I believe in bhmm it should be
> >
> > numpy >= 1.7 (e.g. numpy.random.choice)
> > scipy >= 0.11 (used in the msm package, although that will at some point
> > no longer be needed when pyEMMA has the new reversible transition matrix
> > sampler activated)
> >
>
> Sounds great. How about @marscher fixes the conda recipes for `pyemma` and
> I'll handle the updates for `bhmm`?
>
> Again, we're just stating the minimum required versions of direct
> dependencies. The constraint solver will do the rest.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/188#issuecomment-99515722>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
@jchodera see omnia-md/conda-recipes#189

**Comment by jchodera** [comment]
Thanks, @marscher and @franknoe!

**Pull request merged**
