### PR TITLE
Added travis-ci badge to README.md

### PR DESCRIPTION
**Pull request by jchodera**
This just adds a badge to the `README.md` to report on the travis-ci build status.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Even though it's failing, I think it makes sense to merge.

**Comment by rmcgibbo** [comment]
(once the jenkins builds are running, you should put up a badge for them on the README. It makes it easier to find the links, especially given that it seems like many of the projects on jenkins.choderalab.org are no longer really current).

**Comment by jchodera** [comment]
Great idea!  Sorry for not having done this earlier.  Will submit a PR.

**Comment by jchodera** [comment]
Done!

**Comment by jchodera** [comment]
I'm going to shelve most of the irrelevant projects on Jenkins soon...

**Pull request merged**
