### PR TITLE
ambermini static

### PR DESCRIPTION
**Pull request by rmcgibbo**
So this change, on my machine where I've trashed the file `libquadmath.0.dylib` from my homebrewed-gfortran, which causes the linker to statically link to libquadmath, produces a static build.

I can upload the binary to binstar.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
But this is obviously not portable.

**Comment by kyleabeauchamp** [comment]
OK.  And so the idea is to just append CUSTOMBUILDFLAGS to LDFLAGS and do manual builds for now?

**Comment by rmcgibbo** [comment]
No, the ambermini makefile uses `CUSTOMBUILDFLAGS` itself. You don't have to append it to anything. You just need to run this recipe with a carefully-broken version of gfortran installed in the precise location `/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/`.

**Comment by kyleabeauchamp** [comment]
Got it

**Comment by rmcgibbo** [comment]
Okay. I uploaded the file to https://binstar.org/omnia/ambermini/files.

**Comment by jchodera** [comment]
What about installing gfortran as a conda package as an alternative?

**Comment by rmcgibbo** [comment]
That sounds like a lot of work...

**Comment by rmcgibbo** [comment]
Compilers are generally the hardest piece of software to compile.

**Comment by kyleabeauchamp** [comment]
Sounds like a major project.  If that were easy to do, the Continuum people would have done it.

**Comment by kyleabeauchamp** [comment]
Sounds good, but we probably need to IFDEF that flag so that it doesn't occur on linux:

```
gfortran: /usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/libquadmath.a: No such file or directory
gfortran: /usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/libquadmath.a: No such file or directory
make[1]: *** [dasum.o] Error 1
make[1]: Leaving directory `/home/vagrant/miniconda/conda-bld/work/ambermini-v.14.0.1/blas'
make: *** [libs] Error 2
Command failed: /bin/bash -x -e /home/vagrant/rmc/conda-recipes-ambermini/ambermini/build.sh
```

**Pull request merged**
