### PR TITLE
Update PDBFixer to 1.5

### PR DESCRIPTION
**Pull request by peastman**
@Lnaden could you confirm my changes are correct to generate the beta of 1.5?

### CODE REVIEW

**Comment by Lnaden** [comment]
That should upload PDBFixer 1.5 to the `beta` tag on the anaconda cloud.

**Comment by Lnaden** [comment]
I don't think however that the conda-build-all script will actually find the openmm version because openmm 7.2 is on `beta`, and the build script does not look for the `beta` tag.

**Comment by peastman** [comment]
What do I need to do to make it build the PDBFixer beta against the OpenMM beta?

**Comment by Lnaden** [comment]
I don't think we've ever engineered a solution for that. I think this is the first time it has come up. It should be possible through to extend the conda-build-all script to look in the `extra` section for a flag we can engineer though

**Comment by peastman** [comment]
That could work, though I have no idea how to do it.  Is that something you can do?  The issue here is that OpenMM, PDBFixer, and OpenMM-Setup all basically move as a unit.  Having created an OpenMM beta, we now need a PDBFixer beta that depends on it, and an OpenMM-Setup beta that depends on both of the others.

**Comment by Lnaden** [comment]
I'm not 100% sure either since I did not make the original script, but I can take a stab at that tonight, might take me a couple hours to figure something out though

**Comment by peastman** [comment]
Thanks!

**Comment by Lnaden** [comment]
xref #843 which would enable the features discussed here

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
