### PR TITLE
[WIP] Upgrading Openbabel to 2.4.1 and fixing segfaults

### PR DESCRIPTION
**Pull request by rbharath**
Upgrades openbabel to 2.4.1, and attempts to dealt with some nasty openbabel+sklearn segfaults https://github.com/deepchem/deepchem/issues/329.

Marking [WIP] for now as I debug the issues going on here.

### CODE REVIEW

**Comment by jchodera** [comment]
Shoot, it shouldn't be rebuilding `openmm`. Let me fix that in a separate PR. Sorry about this! I left the force flag on.

**Comment by jchodera** [comment]
@rbharath : Can you merge from master or rebase now that #660 has been committed? This will disable the building of `openmm`.

**Comment by jchodera** [comment]
@rbharath : Can you merge from master or rebase now that #660 has been committed? This will disable the building of openmm.

**Comment by rbharath** [comment]
@jchodera Ok, will do later today.

**Comment by rbharath** [comment]
Hmm, the merge is getting ugly here. I'll just close this for now (the ob version upgrade can be done in a fresh PR).

**Pull request closed without merging**
