### PR TITLE
Update omnia build system to CUDA 9.0 and force openmm 7.2 beta build

### PR DESCRIPTION
**Pull request by jchodera**
This PR makes some more changes in #837 
- [x] Update omnia build system to CUDA 9.0
- [x] Force openmm 7.2 beta to build and push (which may displace `dev`?)

### CODE REVIEW

**Comment by jchodera** [comment]
We forgot to update the build test:
```
===== testing package: openmm-7.2.0-py27_0 =====

running run_test.py

Traceback (most recent call last):

  File "/Users/travis/anaconda/conda-bld/openmm_1512375518239/test_tmp/run_test.py", line 34, in <module>

    assert openmm.Platform.getOpenMMVersion() == '7.1.1', "openmm.Platform.getOpenMMVersion() = %s" % openmm.Platform.getOpenMMVersion()

AssertionError: openmm.Platform.getOpenMMVersion() = 7.2
```

**Comment by Lnaden** [comment]
Odd. This appears to be trying to compile against all the different Numpy versions, but then not relabeling the builds, despite only needing *a* version of numpy installed, so it times out since it winds up building OpenMM 9 times on travis.

**Comment by jchodera** [comment]
Any ideas?

**Comment by jchodera** [comment]
We can merge it anyway and get the beta built and then debug from there.

**Comment by Lnaden** [comment]
> We can merge it anyway and get the beta built and then debug from there.

Just to get something up, sure, probably a good idea. Might result in a few builds we have to delete before converting them to main.

> Any ideas?

Its probably something in conda or conda-build that changed which broke the way the conda-build-all script handles dependency processing. It might just be as simple as its returning a list of 9 blanks (hence why its not trying to upload `openmm_pyX.Y_npA.B.tar.gz` packages, which would be simple enough to fix, but annoying to debug. Just a guess though

**Comment by jchodera** [comment]
Can you merge @lnaden? We'll watch what happens

**Comment by Lnaden** [comment]
Odd, I can't replicate this multiple-builds for the same version error anymore, it also does not look like its in the travis builds anymore. So I'm going to chalk it up to some oddity with the conda-servers? We can reassess if it crops up again.

**Pull request merged**
