### PR TITLE
New smarty release

### PR DESCRIPTION
**Pull request by davidlmobley**
Update meta.yaml for smarty to current version (we'd forgotten to do this in a while).

@limn1, this would fix your issue.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@jchodera , please review and merge.

**Comment by jchodera** [comment]
We're still [fixing a major issue with `conda-build`](https://github.com/omnia-md/conda-recipes/pull/671). Stay tuned.

**Comment by jchodera** [comment]
Thanks!

In future, name the PR something like "[smarty] 0.1.4 release".

**Comment by jchodera** [comment]
New packages are up!
https://anaconda.org/omnia/smarty/files

**Pull request merged**
