### PR TITLE
MSMExplorer 0.3.0

### PR DESCRIPTION
**Pull request by cxhernandez**

### CODE REVIEW

**Comment by cxhernandez** [comment]
Not sure why OSX builds but Linux doesn't.

**Comment by jchodera** [comment]
Retriggered builds. 

We had a spate of those PyQT4 errors before. I'm not sure exactly which upstream dependency was the cause.

**Comment by cxhernandez** [comment]
Seems to happen consistently (I had retriggered before). The error is coming from `matplotlib` but it built perfectly fine in the MSMExplorer Travis tests, which uses the same version of `matplotlib` and `pyqt`.

**Comment by jchodera** [comment]
Merging. Hopefully this won't cause issues!

**Comment by cxhernandez** [comment]
Looks like it worked on master! Weird!

**Comment by jchodera** [comment]
Did it really build all the versions? I think there are some missing versions:
```
===== testing package: msmexplorer-0.3.0-py35_0 =====
import: 'msmexplorer'
Traceback (most recent call last):
  File "/anaconda/conda-bld/msmexplorer_1477676714197/test_tmp/run_test.py", line 27, in <module>
    import msmexplorer
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/msmexplorer/__init__.py", line 1, in <module>
    from .plots import *
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/msmexplorer/plots/__init__.py", line 1, in <module>
    import seaborn
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/seaborn/rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/seaborn/utils.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/anaconda/conda-bld/msmexplorer_1477676714197/_t_env/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
TESTS FAILED: msmexplorer-0.3.0-py35_0
ERROR: File does not exist: /anaconda/conda-bld/linux-64/msmexplorer-0.3.0-py35_0.tar.bz2
[conda-build-all] Error: one or more packages failed to build (linux-64)
  msmexplorer-0.3.0-py34_0.tar.bz2
  msmexplorer-0.3.0-py35_0.tar.bz2
```

**Pull request merged**
