### PR TITLE
OpenMM post-link logic.

### PR DESCRIPTION
**Pull request by rmcgibbo**
This is the companion to https://github.com/pandegroup/openmm/pull/780, with the necessary post-link code that modifies `version.py` so that `version.openmm_library_path` gives the correct plugin directory at runtime, which is a value that we can't know at compile time because different users have anaconda/miniconda installed in different places.

### CODE REVIEW

**Comment by jchodera** [comment]
Weird---there was some sort of failure in the travis test:
https://travis-ci.org/omnia-md/conda-recipes/builds/46939887#L1495-L1504
```
Traceback (most recent call last):
  File "./conda-build-all", line 221, in <module>
    main()
  File "./conda-build-all", line 65, in main
    execute(args, p)
  File "./conda-build-all", line 202, in execute
    metadata = MetaData(recipe)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 241, in __init__
    assert isdir(path)
AssertionError
```
I haven't seen this before.  Is this something that should be ignored?

**Comment by rmcgibbo** [comment]
same with https://github.com/omnia-md/conda-recipes/pull/115

**Comment by jchodera** [comment]
OK, we can debug/fix in a separate PR!

**Comment by rmcgibbo** [comment]
I think I need to talk to @peastman more tomorrow before merging this.

**Comment by jchodera** [comment]
Sorry about that.

Can we mark works in progress as [WIP] in future, or agree on a "ready to
merge" go?

**Comment by rmcgibbo** [comment]
> Can we mark works in progress as [WIP] in future, or agree on a "ready to merge" go?

Yeah, my fault there.

**Pull request merged**
