### PR TITLE
Changed OpenMM recipe to build osx version with 10.7 SDK instead of 10.9

### PR DESCRIPTION
**Pull request by jchodera**
This addresses https://github.com/pandegroup/openmm/issues/881

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
+1

**Comment by jchodera** [comment]
Any idea why this is erroring?

**Comment by jchodera** [comment]
It's timing out trying to download packmol:
https://travis-ci.org/omnia-md/conda-recipes/builds/59592683#L1545-L1560

Can we put a local cache of this somewhere?

**Comment by kyleabeauchamp** [comment]
Is this the first time we've had a problem with packmol?  If it's the first time, I'd say try to rebuild the travis rather than doing more customization of our CI tools.  

If this has been causing problems repeatedly, then we can follow the model here: https://github.com/mdtraj/mdtraj/blob/master/devtools/travis-ci/install.sh#L27

**Comment by jchodera** [comment]
Haven't seen this before. I've triggered a travis rebuild.

**Comment by rmcgibbo** [comment]
You should increment the build number in the `meta.yaml` too, I think.

**Comment by jchodera** [comment]
Good catch!

**Comment by jchodera** [comment]
Seems to pass.  Committing.

**Comment by jchodera** [comment]
We should change the `openmm-dev` recipe too.  On it.

**Pull request merged**
