### PR TITLE
Manually install LatTeX packages to build OpenMM docs

### PR DESCRIPTION
**Pull request by Lnaden**
Sphinx decided to no longer ship the fncychap LaTeX package starting in 1.5, but still make use of it. So to get it, we have to manually install it. It would probably be good to add this to the Docker image at some point.

### CODE REVIEW

**Comment by Lnaden** [comment]
Running list of manually installed LaTeX packages in case more crop up:
* fncychap
* tabulary

**Comment by Lnaden** [comment]
Okay, this if finally building OpenMM, but this PR should be reviewed by a couple people since its rather hack-y and patches the OpenMM 7.1rc1 release's docs to compile correctly.

The main problem is that if we want OpenMM 7.1 on Python 3.6 we have to update Sphinx and make some small changes. We can either make those changes here on the publisher side, or change them in the OpenMM code and cut another build, which I imagine is less favorable.

**Summary of changes**
* Several LaTeX packages are added to the build environment since Sphinx 1.5+ no longer ships them.

**Questions for Review**
* Is this patch for OpenMM's docs okay for cutting the Python 3.6 release of 7.1? We will also want to make a PR for OpenMM directly to bring this change in for the next release
* Is not having the `git` hash match for this build acceptable because of the patch acceptable?
* How required is it to ship missing LaTeX packages that Sphinx no longer requires (related issue #725)?
* Do people approve of the additional LaTeX packages in the build in general?

Tagging @peastman @jchodera @jlmaccal

**Comment by Lnaden** [comment]
Any feed back on this? It is kind of holding up the entire distribution system at the moment

**Comment by peastman** [comment]
It is indeed quite a hack!  But for the moment I suppose it's as reasonable as anything.

**Comment by Lnaden** [comment]
Okay, I'll merge this just to get the build going, we can fix this more elegantly later and push a new build if we need to.

**Comment by Lnaden** [comment]
And thanks for looking at this @peastman

**Pull request merged**
