### PR TITLE
[WIP] Update omnia metapackage to trigger automatic builds of omnia packages and dependencies

### PR DESCRIPTION
**Pull request by jchodera**
This attempts to implement a suggestion from @kyleabeauchamp made in #71.

Still testing.

### CODE REVIEW

**Comment by jchodera** [comment]
It identifies the dependencies all right, but doesn't seem to be able to build `scripttest`, a dependency of a number of packages, despite the fact that the `scriptbuilder` recipe is right there:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/11/console
```
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np18py27_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np19py27_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np18py33_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np19py33_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np18py34_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
BUILD START: omnia-0.1-0
Fetching package metadata: ...
Missing dependency msmbuilder, but found recipe directory, so building msmbuilder first
BUILD START: msmbuilder-3.0b1-np19py34_0
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by kyleabeauchamp** [comment]
Is this because MDTraj lists scripttest under `run` but not `build`?  E.g.


```
requirements:
build:
- python
- cython
- numpy
- setuptools
run:
- python
- numpy
- scipy
- pandas
- scripttest
```

**Comment by kyleabeauchamp** [comment]
If so, perhaps you can manually add `scripttest` to the build section of the omnia recipe?  That is, we can use the recipe to force builds of any extra dependencies that might be overlooked.

**Comment by jchodera** [comment]
That just might do the trick.  Will try this strategy...

**Comment by jchodera** [comment]
This seems to have worked to some degree:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/13/console

Building of the omnia package and dependencies (python 2.7 numpy 1.8 versions) succeeded, but it did not build other python/numpy combinations.

Any more ideas here?

**Comment by rmcgibbo** [comment]
This is fixed now by building everything in the proper order, and not relying on conda-build to linearize the dependency chain.

**Pull request closed without merging**
