### PR TITLE
Added ensembler recipe

### PR DESCRIPTION
**Pull request by danielparton**

### CODE REVIEW

**Comment by danielparton** [comment]
Note: runtime requirement `subprocess32` is not available through the default conda channels. However, the current version of the `ensembler` recipe does not run tests, so this should not be a problem for now.

I'll try to think of a workaround which could be implemented in a future version of this recipe.

**Comment by kyleabeauchamp** [comment]
Will merge once travis done

**Comment by jchodera** [comment]
Can we add a recipe for subprocess32?

**Comment by jchodera** [comment]
subprocess32 is on pypi, so you should be able to trivially create a conda
recipe using 'conda skeleton' and add that to omnia:

http://conda.pydata.org/docs/commands/build/conda-skeleton.html

**Comment by kyleabeauchamp** [comment]
@danielparton  and I discussed this and thought it makes sense to postpone for now, as we're still discussing the various ways to incorporating these features.

**Comment by danielparton** [comment]
Ok, I've added a recipe for `subprocess32` - waiting for Travis now.

**Comment by jchodera** [comment]
Tests pass, so merging!

**Pull request merged**
