### PR TITLE
[propertyestimator] 0.0.4 (label: rc)

### PR DESCRIPTION
**Pull request by SimonBoothroyd**

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
Tagging @j-wags

**Comment by j-wags** [comment]
Do you want to merge once Travis runs, or shall I?

**Comment by j-wags** [comment]
@SimonBoothroyd FYI -- Builds look good, and this should be good to merge when you're ready.

**Comment by SimonBoothroyd** [comment]
@j-wags thanks!

**Pull request merged**
