### PR TITLE
bhmm

### PR DESCRIPTION
**Pull request by rmcgibbo**
@jchodera are there other problems with the bhmm package? i needed to add mock to get it to build on my machine.

### CODE REVIEW

**Comment by jchodera** [comment]
I'm trying to figure out why it says we need `mock`.  I don't understand what it's trying to do.

Even when I've bumped the version number of the github version in the recipe to `0.3.0`, it says this craziness:
```
writing build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/bhmm-0.2.0-py2.7-macosx-10.5-x86_64.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing bhmm-0.2.0-py2.7-macosx-10.5-x86_64.egg
creating /Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/bhmm-0.2.0-py2.7-macosx-10.5-x86_64.egg
Extracting bhmm-0.2.0-py2.7-macosx-10.5-x86_64.egg to /Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages
Adding bhmm 0.2.0 to easy-install.pth file

Installed /Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/bhmm-0.2.0-py2.7-macosx-10.5-x86_64.egg
Processing dependencies for bhmm==0.2.0
Searching for mock
Traceback (most recent call last):
  File "setup.py", line 164, in <module>
    ext_modules = cythonize(extensions)
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/easy_install.py", line 380, in run
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/easy_install.py", line 610, in easy_install
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/easy_install.py", line 661, in install_item
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/easy_install.py", line 709, in process_distribution
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 830, in resolve
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 1075, in best_match
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 1087, in obtain
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/command/easy_install.py", line 617, in easy_install
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/package_index.py", line 594, in fetch_distribution
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/package_index.py", line 431, in find_packages
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/package_index.py", line 765, in scan_url
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/mock/r
Command failed: /bin/bash -x -e /Users/choderaj/code/omnia/conda-recipes.jchodera/bhmm/build.sh
```
I have no idea where it's getting the `bhmm 0.2.0` info from.

**Comment by rmcgibbo** [comment]
What's the harm in adding mock? That seems like the easiest solution (after adding it, all the tests ran and passed). Otherwise you should probably just remove `install_requires` from the setup.py. That's where all of this is coming from -- that feature of setuptools just sucks.

**Comment by rmcgibbo** [comment]
also, FWIW, my experience is that having conda build from a git-tag should be avoided. better to point it to a tarball, either on github (https://github.com/bhmm/bhmm/archive/0.3.0.tar.gz) or on pypi.

**Comment by jchodera** [comment]
> What's the harm in adding mock?

No harm in adding mock, but it is likely just a symptom of a deeper underlying problem since I don't understand why it should require mock.

> also, FWIW, my experience is that having conda build from a git-tag should be avoided

Thanks.  Will change this.

**Comment by rmcgibbo** [comment]
Are you sure there's a deeper problem? The tests ran just fine when I added it :) #bandaidsforallthethings

**Comment by jchodera** [comment]
> Are you sure there's a deeper problem? 

When I incremented the build source to 0.3.0, it was still trying to build/install `bhmm 0.2.0` as a dependency. Even after cleaning caches and reinstalling conda.  That seemed kind of weird to me.

> Otherwise you should probably just remove install_requires from the setup.py.

Unfortunately, Frank Noe still needs the `PyPI` install route for `bhmm` because it will be a dependency for pyemma.

We are going to later split out the bhmm core from the force spectroscopy stuff so that the minimal `bhmm` features can be used by multiple packages.

Also, I seem to have a competing PR #213

**Comment by rmcgibbo** [comment]
Right. I'll close this. Maybe the 0.2.0 v 0.3.0 thing will go away if you switch to downloading from a tarball instead of git? Not sure.

**Comment by jchodera** [comment]
> Right. I'll close this. 

Thanks!

> Maybe the 0.2.0 v 0.3.0 thing will go away if you switch to downloading from a tarball instead of git? 

Sadly, it didn't.

Adding `mock` as a requirement seems to have worked, but I worry that there is something very broken.

**Comment by jchodera** [comment]
Though...it didn't try to install `bhmm 0.2.0` when I added the mock dependency.

So. Weird.

Thanks for your help!

**Pull request closed without merging**
