### PR TITLE
[progress_reporter] build univeral wheel to avoid conda build bug

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by jchodera** [comment]
Huh. Was the bug affecting windows builds only? Is there a link to the bug issue?

**Comment by marscher** [comment]
slash vs. backslash mistake on my side... 

Bug report is here: conda/conda-build#1209

**Comment by jchodera** [comment]
> Bug report is here: conda/conda-build#1209

Awesome, thanks!

**Comment by marscher** [comment]
cmd.exe never supported wildcard expansion :+1:

**Pull request merged**
