### PR TITLE
[pyemma] updated to 1.1

### PR DESCRIPTION
**Pull request by marscher**
please merge ASAP, I need those conda packages! Thank you!

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good!

**Comment by marscher** [comment]
thanks for the super fast reaction!

**Comment by jchodera** [comment]
Jenkins builds should happen shortly.  Let me know if you see problems:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/

**Comment by jchodera** [comment]
You can thank Deutsche Bahn and Telekom.  For once the internet on the train seems to actually work!

**Comment by marscher** [comment]
unbelievable :)

Bon voyage!

**Pull request merged**
