### PR TITLE
[perses] 0.7.2

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**

### CODE REVIEW

**Comment by jchodera** [comment]
@hannahbrucemacdonald Are you able to build and push this to `omnia`, or do you need one of us to do that?

**Comment by j-wags** [comment]
@jchodera I've built and pushed a package, which SHOULD work on the first go. I'm running py36/37 tests on mac/linux now before I merge this.

**Comment by j-wags** [comment]
@hannahbrucemacdonald @jchodera Mac passes all tests. I'm encountering a test failure on linux, both py36 and 37. Have you seen this before?

Pulling the 0.7.2 package off `main` and on to the `omnia/label/rc` while we discuss. 

```
======================================================================
ERROR: Test that the torsion scan is generating angles that correspond to what openmm calculates. It does this by first generating
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/jrwagner/miniconda3/envs/temp_perses6_36/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/users/jrwagner/perses/perses/tests/test_geometry_engine.py", line 619, in test_torsion_scan
    raise Exception("Torsion scan did not match OpenMM torsion")
Exception: Torsion scan did not match OpenMM torsion

======================================================================
FAIL: Test FFAllAngleGeometryEngine _internal_to_cartesian and _cartesian_to_internal are consistent with OpenMM torsion angles.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/jrwagner/miniconda3/envs/temp_perses6_36/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/users/jrwagner/perses/perses/tests/test_coordinate_numba.py", line 113, in test_openmm_dihedral
    assert np.linalg.norm(openmm_phi - phi) < TORSION_TOLERANCE, msg
AssertionError: _internal_to_cartesian and OpenMM disagree on torsions: 
_internal_to_cartesian generated positions for: -3.141592653589793
OpenMM: 3.141592653589793
positions: [[ 1.27477734  0.10606969 -1.09675394]
 [ 0.0765      0.1        -0.4005    ]
 [ 0.0829      0.0952     -0.2479    ]
 [-0.057       0.0951     -0.1863    ]] nm
```

**Comment by j-wags** [comment]
Understood. Looks like the 0.7.2 package is already on the `main` label (maybe John moved it over).

Since this package is a faithful reproduction of the 0.7.2 tag, I'll merge this PR. 

If you fix the test (and the fix is significant enough to warrant a new release), then we can make a 0.7.3 package pretty quickly.

**Pull request merged**
