### PR TITLE
Update openforcefield for 0.0.4

### PR DESCRIPTION
**Pull request by davidlmobley**
Updates for 0.0.4 release.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@Lnaden @jchodera - it looks like there's an issue with OpenMM in the test here? Doesn't seem to be related to my recipe update.

**Comment by Lnaden** [comment]
I'm not sure why that started failing. I'll have to dig into why that yields an empty tuple

**Comment by jchodera** [comment]
Oof. More conda-build fun

**Comment by davidlmobley** [comment]
@Lnaden - I also pushed an update to the SolvationToolkit recipe and it ended up in this PR as well. As per https://github.com/omnia-md/conda-recipes/pull/864#issuecomment-374916479

**Comment by Lnaden** [comment]
Great! Thanks!

**Comment by Lnaden** [comment]
@davidlmobley can you merge the current master into your fork and re-push to get the fix in `conda-build-all` as per an issue I fixed found in #866 and #867? This should fix the travis Linux tests.

**Comment by davidlmobley** [comment]
Done.

**Comment by Lnaden** [comment]
Thanks!

**Comment by Lnaden** [comment]
Well.. This happened on OSX: `No space left on device`. However, some of the builds did pass for OpenFF and OpenSolvation, so I think this is fine,. I am going to merge and we just will have to run the builds a few times to get them all uploaded. Any problems we can fix after.

**Comment by Lnaden** [comment]
The builds are all posted now. Should be good

**Pull request merged**
