### PR TITLE
build bhmm on all platforms

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
Hm, something seems wrong:
```
TEST START: bhmm-0.5.0-np19py34_0
Fetching package metadata: ........ 
Solving package specifications: .===== testing package: bhmm-0.5.0-np19py34_0 =====
import: 'bhmm'
Traceback (most recent call last):
  File "C:\Python34_64\conda-bld\test-tmp_dir\run_test.py", line 25, in <module>
    import bhmm
ImportError: No module named 'bhmm'
```

**Comment by marscher** [comment]
It seems like there is no build performed at all. At first glance I
thought it might be due to a missing build.bat, when I noticed none of
omnias recipes has one... I have no clue, why conda-build does not
perform the build at all.

**Comment by marscher** [comment]
ah the windows build script names bld.bat, not build.bat what I've
expected. Now it should work.

**Comment by rmcgibbo** [comment]
```
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./bhmm/_external/clustering/include -IC:\Python34_64\envs\_build\lib\site-packages\numpy\core\include -IC:\Python34_64\envs\_build\include -IC:\Python34_64\envs\_build\include /Tc./bhmm/_external/clustering/src/kmeans.c /Fobuild\temp.win-amd64-3.4\Release\./bhmm/_external/clustering/src/kmeans.obj -std=c99
cl : Command line warning D9002 : ignoring unknown option '-std=c99' 
kmeans.c
c:\python34_64\envs\_build\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION 
./bhmm/_external/clustering/src/kmeans.c(112) : warning C4028: formal parameter 1 different from declaration 
./bhmm/_external/clustering/src/kmeans.c(112) : warning C4028: formal parameter 2 different from declaration 
./bhmm/_external/clustering/src/kmeans.c(261) : warning C4244: 'function' : conversion from 'time_t' to 'unsigned int', possible loss of data 
./bhmm/_external/clustering/src/kmeans.c(288) : warning C4028: formal parameter 1 different from declaration 
./bhmm/_external/clustering/src/kmeans.c(288) : warning C4028: formal parameter 2 different from declaration 
./bhmm/_external/clustering/src/kmeans.c(320) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data 
./bhmm/_external/clustering/src/kmeans.c(362) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data 
./bhmm/_external/clustering/src/kmeans.c(419) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data 
./bhmm/_external/clustering/src/kmeans.c(577) : error C2143: syntax error : missing ';' before 'type' 
./bhmm/_external/clustering/src/kmeans.c(579) : error C2065: 'st' : undeclared identifier 
./bhmm/_external/clustering/src/kmeans.c(579) : error C2223: left of '->error' must point to struct/union 
./bhmm/_external/clustering/src/kmeans.c(580) : error C2065: 'st' : undeclared identifier 
./bhmm/_external/clustering/src/kmeans.c(580) : error C2223: left of '->error' must point to struct/union 
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
 
C:\Python34_64\conda-bld\work>if errorlevel 1 exit 1 
```

**Comment by marscher** [comment]
this has been fixed, but not yet released. Sorry!

**Comment by marscher** [comment]
@jchodera shall we release 0.5.1 for the kmeans compilation fix? I can
do it, if desired.

**Comment by jchodera** [comment]
@marscher: Go for it.

**Comment by marscher** [comment]
done.

**Pull request merged**
