### PR TITLE
Fix linearize

### PR DESCRIPTION
**Pull request by rmcgibbo**
1. Contains fix for the #82, without waiting for the upstream bugfix for conda-build that I filed.
2. Changes the order of iteration in conda-build-all, so that the inner loop is over the recipes and the outer loop is over python versions. This makes it easier to identify dependency resolution failures early
3. No more inline `build: script: python setup.py install`, because this prevents mocking out, ala #86)
4. Fix to an issue with the jype1 build. From https://binstar.org/omnia/jpype1/files, you can see that the python version wasn't included in the build string, even though it should have been.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome. Is this ready to merge?

**Comment by rmcgibbo** [comment]
Yep. I try adding the travis-ci / mock thing in a separate PR.

**Comment by jchodera** [comment]
Rebuilding on jenkins using these new build script.

I presume I can eliminate the repeated calls to the build script from the jenkins configurations?

**Comment by rmcgibbo** [comment]
I think so, but not 100% sure.

**Comment by rmcgibbo** [comment]
There are still some issues on py33 with unsatisfiable specs.... could be related to https://github.com/conda/conda-build/issues/289.

**Comment by jchodera** [comment]
Is this sorted now that the travis-ci passes?

**Pull request merged**
