### PR TITLE
Require development openmm (6.3) which ParmEd needs

### PR DESCRIPTION
**Pull request by davidlmobley**

### CODE REVIEW

**Comment by jchodera** [comment]
@rmcgibbo : It looks like appveyor 64-bit is failing on msmbuilder for due to some unresolved symbols.  Could that be a fluke, or is this a known issue?
https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.90/job/fqe9we214us1kvec#L917
```
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _mm_cvt_pi2ps referenced in function _mm_cvtpi32x2_ps
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_empty referenced in function "union __m128 __cdecl log_ps(union __m128)" (?log_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_psubd referenced in function "union __m128 __cdecl log_ps(union __m128)" (?log_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_psrldi referenced in function "union __m128 __cdecl log_ps(union __m128)" (?log_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_pslldi referenced in function "union __m128 __cdecl exp_ps(union __m128)" (?exp_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_paddd referenced in function "union __m128 __cdecl exp_ps(union __m128)" (?exp_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _mm_cvtt_ps2pi referenced in function "union __m128 __cdecl exp_ps(union __m128)" (?exp_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_pcmpeqd referenced in function "union __m128 __cdecl sin_ps(union __m128)" (?sin_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _mm_setzero_si64 referenced in function "union __m128 __cdecl sin_ps(union __m128)" (?sin_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_pand referenced in function "union __m128 __cdecl sin_ps(union __m128)" (?sin_ps@@YA?AT__m128@@T1@@Z)
GaussianHMMCPUImpl.obj : error LNK2019: unresolved external symbol _m_pandn referenced in function "union __m128 __cdecl cos_ps(union __m128)" (?cos_ps@@YA?AT__m128@@T1@@Z)
build\lib.win-amd64-3.4\msmbuilder\hmm\_ghmm.pyd : fatal error LNK1120: 11 unresolved externals
```

**Comment by rmcgibbo** [comment]
Not surprising really. I don't think we've had the project passing on py3 (vs2010) win-64 in the past, or now.

**Comment by jchodera** [comment]
Want to add `win-64` to a `skip.yaml` for msmbuilder?

**Comment by rmcgibbo** [comment]
sure, that's fine.

**Comment by rmcgibbo** [comment]
The file that's broken, `GaussianHMMCPUImpl`, is actually not even in the next release. @peastman completely rewrote the hmm code. so when we release next, this problem might just go away naturally.

**Comment by jchodera** [comment]
Ah, OK.  I just created #230, but we can pass if it would be a pain to undo.

**Pull request merged**
