### PR TITLE
Release msmbuilder 3.4

### PR DESCRIPTION
**Pull request by mpharrigan**
And sync requirements with our CI requirements

### CODE REVIEW

**Comment by mpharrigan** [comment]
Is the gfortran error on linux related to all the other gfortran chatter I see? I can't reproduce the error locally with that configuration

**Comment by mpharrigan** [comment]
Oh wait, I can reproduce locally. Investigating

**Comment by jchodera** [comment]
I think @andrrizzi observed that this dependency was introduced by the recent `scipy 0.17`. It's possible that pinning to `scipy 0.16` will solve the issue for you.

**Comment by mpharrigan** [comment]
I fixed it, see https://github.com/omnia-md/conda-recipes/pull/474/commits/439f0332a8f86b1fb2de122a032a5bdd9b629072

**Comment by mpharrigan** [comment]
newer scipy uses newer libfortran (v3 to be exact)

**Comment by mpharrigan** [comment]
Ready for merge!

**Pull request merged**
