### PR TITLE
No jinja2/markupsafe on appveyor?

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by mpharrigan** [comment]
What?

**Comment by rmcgibbo** [comment]
This is one way to fix the markupsafe rm_rf error.

**Comment by jchodera** [comment]
LOL:
```
Build started
git clone -q https://github.com/omnia-md/conda-recipes.git C:\projects\conda-recipes
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; result=18, HTTP code = 200
Command exited with code 128
```
Restart appveyor?

**Comment by jchodera** [comment]
Or should this be `crapveyor`?

**Comment by rmcgibbo** [comment]
This jinja2/markupsafe/access denied issue was fixed upstream in https://github.com/conda/conda-build/pull/521. IIRC they usually cut a release every week or so, so it should be fixed soon for us.

**Comment by rmcgibbo** [comment]
(Without this PR)

**Pull request merged**
