### PR TITLE
Update Lomap recepie. PyQt4 is needed

### PR DESCRIPTION
**Pull request by nividic**
I updated the PyQt version required and the new Lomap git home page

### CODE REVIEW

**Comment by nividic** [comment]
The Linux and Mac tests are failing because OpenMM is not correctly installed in the test environment. My project does not require OpenMM at all. The Windows tests are failing as well. In my original lomap recipe I disabled windows but someone else has changed my original skip section. Can someone help with these
 problems please?

**Comment by jchodera** [comment]
The windows build is still being skipped, so you can ignore the failures on appveyor.

Your recipe actually fixes the lomap failures, so I'm going to go ahead and merge it. The remaining failures are unrelated. Thanks!

When do you plan to add python 3.x support? We are going to need all omnia packages to comply with that at this stage.

**Comment by davidlmobley** [comment]
We're working towards adding python 3.x support, @jchodera - Gaetano is trying to get it in in his "spare time" in the evening in the near future.

**Comment by nividic** [comment]
I'm trying to port Lomap to python3. Unfortunately there is a problem that I cannot think I can fix. In a particular Rdkit library Chem/Draw there is a dependence on the Python Image Library (PIL http://www.pythonware.com/products/pil/) which does not support python3 yet. I send to the developers an email asking about that. The library is quite important to generate molecule depictions that are used to display and output a .png file of the planned alchemical mutation mapping. The alternative would be to generate just a graphviz .dot file.

**Comment by davidlmobley** [comment]
@nividic - I think the priority is to get Python 3 compatibility in, regardless of whether the visualization is retained. I suggest you just make it output a `.dot` file and create an issue on the LOMAP github to resolve visualizations with Python 3 once PIL is Py3 compatible.

**Pull request merged**
