### PR TITLE
Paramz

### PR DESCRIPTION
**Pull request by cxhernandez**
adding paramz for https://github.com/omnia-md/conda-recipes/pull/454

### CODE REVIEW

**Comment by jchodera** [comment]
Coolio!

@pgrinaway and @maxentile might be interested in this too.

**Comment by mpharrigan** [comment]
Did you mean to pull in that other commit?

**Comment by cxhernandez** [comment]
No, I wanted to make sure this one would build and be uploaded to conda before the other one.

**Comment by jchodera** [comment]
I think he might mean the `prerelease` stuff?
```
+    if is_prerelease(m):
 +        cmd.extend(['--label', 'pre'])
```

**Comment by cxhernandez** [comment]
Ahh, yeah idk how that got in there.... lemme fix that

**Comment by jchodera** [comment]
Maybe just merge in master (@rmcgibbo added these by direct commits) or rebase?

**Comment by cxhernandez** [comment]
I'm not sure what @rmcgibbo did but it's a bit of a headache....

**Comment by cxhernandez** [comment]
Okay! I think it's good now.

**Comment by jchodera** [comment]
Yay! Thanks. Will just wait for travis to finish.

**Pull request merged**
