### PR TITLE
[pyemma] bump to v2.1rc1

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
failed because of not respecting utf8 encoding of our readme.

**Comment by marscher** [comment]
I do not understand, where an error occurred?
https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/job/v5mc3mxiyox2rpfb

**Comment by marscher** [comment]
ping @clonker

**Comment by marscher** [comment]
for win-32 py35:

Error: Unsatisfiable package specifications.
....
Hint: the following packages conflict with each other:
  - python 3.5*
  - mdtraj >=1.6
  - numpy 1.9*

ping @rmcgibbo Does this mean mdtraj-1.6 is not being available for py35-win32-np19?

**Comment by mpharrigan** [comment]
It looks like all the mdtraj builds went fine https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.627

**Comment by mpharrigan** [comment]
And the files are there https://anaconda.org/omnia/mdtraj/files

**Comment by marscher** [comment]
You're right, thank you. Very strange though...

**Comment by rmcgibbo** [comment]
You might try using conda-hint which was a little script I wrote that you
can find on github.

**Comment by marscher** [comment]
Thank you Robert! Will try it.

**Comment by marscher** [comment]
``` conda-hint  'numpy 1.9*' 'mdtraj 1.6*' 'python 3.5*' -p win-32 ``` marks pytables red, which I understand as not satisfiable.

**Comment by rmcgibbo** [comment]
so probably there is no pytables package for numpy1.9, py35, win-32.

**Comment by marscher** [comment]
does this skip.yml infrastructure still exists? :)

**Comment by marscher** [comment]
or: if we merge this now, there will be now build for py35-np19 on win-32 (which with I'm ok with).

**Comment by rmcgibbo** [comment]
there's skip syntax in meta.yaml: e.g.  https://github.com/omnia-md/conda-recipes/blob/ff32045ffe5ffa3403ce62d2ea5af84c76d375a8/pymol/meta.yaml#L11-L13

**Pull request merged**
