### PR TITLE
Fix the tests for scs to work with numpy 1.12

### PR DESCRIPTION
**Pull request by Lnaden**
@rmcgibbo as the one who added the original scs, do these changes look good to you?

### CODE REVIEW

**Comment by Lnaden** [comment]
The windows failures appear to be related to other packages not building on Python3.5/.6. Does anyone see something else in the AppVeyor errors that would cause concern?

**Comment by rmcgibbo** [comment]
Yes, this looks good to me.

**Comment by Lnaden** [comment]
The SCS builds are passing. If the other errors are acceptable to others, this can be merged since these changes only affect SCS.

**Comment by Lnaden** [comment]
The only tests failing are for not scs, merging this so we can keep debugging other builds.

**Pull request merged**
