### PR TITLE
Adding some dependencies for building openmm docs

### PR DESCRIPTION
**Pull request by jchodera**
cc: https://github.com/omnia-md/conda-dev-recipes/pull/1

### CODE REVIEW

**Comment by rmcgibbo** [comment]
you might turn the `noarch_python: True` on for these, since they're just pure python. For the wheels on pypi, I did the pip-equivalent thing (e.g. "sphinxcontrib_autodoc_doxygen-0.3.1-py2.py3-none-any.whl" on https://pypi.python.org/pypi/sphinxcontrib-autodoc_doxygen/0.3.1)

**Comment by jchodera** [comment]
How is 1.10.0 not >= 1.4.1???
```
BUILD START: sphinxcontrib-lunrsearch-0.2-py_0
Fetching package metadata: ..................

WARNING: conda-build appears to be out of date. You have version 1.15.0 but the
latest version is 1.18.2. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .....................
The following NEW packages will be INSTALLED:

...
    six:              1.10.0-py27_0
...

Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%
Removing old work directory
Source cache directory is: /Users/choderaj/anaconda/conda-bld/src_cache
Found source in cache: release.zip
Extracting download
Package: sphinxcontrib-lunrsearch-0.2-py_0
source tree in: /Users/choderaj/anaconda/conda-bld/work/sphinxcontrib-lunrsearch-0.2
+ /Users/choderaj/anaconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    'six>=1.4.1',
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/dist.py", line 268, in __init__
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/dist.py", line 312, in fetch_build_eggs
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1091, in best_match
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1103, in obtain
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/dist.py", line 379, in fetch_build_egg
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 627, in easy_install
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/package_index.py", line 605, in fetch_distribution
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/package_index.py", line 442, in find_packages
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/package_index.py", line 776, in scan_url
  File "/Users/choderaj/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/package_index.py", line 284, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools_scm/r
Command failed: /bin/bash -x -e /Users/choderaj/github/omnia/conda-recipes/conda-recipes.jchodera/sphinxcontrib-lunrsearch/build.sh
```

**Comment by rmcgibbo** [comment]
it's not `six` -- the linenumber in the traceback is just wrong. `RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools_scm/r`.

also, i usually find it's quicker to debug these on my laptop, just by running `conda build`.

**Comment by jchodera** [comment]
> also, i usually find it's quicker to debug these on my laptop, just by running conda build <recipe-dir>.

Just remembered I could do that.  Thanks!

**Pull request merged**
