### PR TITLE
[openmm 7.0.1] build based on git hash 5e86c4f

### PR DESCRIPTION
**Pull request by jchodera**
See https://github.com/pandegroup/openmm/issues/1489

### CODE REVIEW

**Comment by jchodera** [comment]
This should go to the `rc` label.

**Comment by jchodera** [comment]
For some reason, OpenMM 7.0.1 didn't get built upon merge.

@marscher: Any idea why?

**Comment by rmcgibbo** [comment]
I would guess because "7.0rc1" sorts in front of "7.0.1".

**Comment by jchodera** [comment]
@marscher: Did you run into this problem too when you used the old pre label? When you moved it to main, did you have trouble with X.Yrc1 sorting ahead of X.Y.Z?

I suppose we could add some feature to conda-build-all to let us force the build of any package that isn't already in anaconda cloud, rather than just packages that are more up to date than what is on anaconda cloud? If the sorting problem is real, we would have to figure out how to replace OpenMM 7.0rc1 safely before moving on, though.

**Comment by marscher** [comment]
Am 25.05.2016 um 07:29 schrieb Robert T. McGibbon:
> I would guess because "7.0rc1" sorts in front of "7.0.1".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/omnia-md/conda-recipes/pull/531#issuecomment-221476755>
>
Well I thought the behaviour is like the following: if the package is not found in the specified conda channels, a build will be triggered, no matter if it is a 
old version or a recent one? Of course we only have the "current" git head, which points to the desired version to build.

**Comment by jchodera** [comment]
> Well I thought the behaviour is like the following: if the package is not found in the specified conda channels, a build will be triggered, no matter if it is a old version or a recent one?

The recipe just added is for `openmm-7.0.1`, but it does not seem to be building because `openmm-7.0rc1` is present.

I'll open a new pull request to get some more debug information about what is going on.

**Comment by jchodera** [comment]
cc https://github.com/omnia-md/conda-recipes/pull/533

**Pull request merged**
