### PR TITLE
Build OpenMM 7.2rc2

### PR DESCRIPTION
**Pull request by peastman**
@jchodera @Lnaden is this correct, or do I also have to set `force_upload` to `True`?

### CODE REVIEW

**Comment by jchodera** [comment]
Incrementing the build number *should* force re-upload.

**Comment by Lnaden** [comment]
Yes, the build numbers let you rebuild when there have been changes to the code base, but not the version. If someone tries to install "the most recent version," or even the same version number, it will prioritize the higher build number

**Comment by peastman** [comment]
Thanks!

One of the travis builds failed right at the start:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

I'll try restarting it.

**Comment by jchodera** [comment]
Whoops, that gets me every time!

**Comment by peastman** [comment]
It uploaded two of the Mac installers fairly soon after I merged this, but there's been nothing else for a few hours.  How do I check what it's doing?

https://anaconda.org/omnia/openmm/files

**Comment by jchodera** [comment]
Check the Travis output for the master branch:
https://travis-ci.org/omnia-md/conda-recipes

**Comment by Lnaden** [comment]
It looks like it hit the maximum allowed Travis wall clock time midway through the Python 3.6 builds, so those versions never finished and never pushed. If we were to restart the jobs, it should correctly see that Python 2.7 and 3.5 are built, skip those, and proceed to the python 3.6 build as desired.

**Comment by peastman** [comment]
I restarted them.

**Comment by peastman** [comment]
Everything built.  Thanks!

**Pull request merged**
