### PR TITLE
Docker and OS X

### PR DESCRIPTION
**Pull request by rmcgibbo**
https://travis-ci.org/rmcgibbo/conda-recipes

### CODE REVIEW

**Comment by jchodera** [comment]
Whoa, what image is `phusion/holy-build-box-64`?

**Comment by jchodera** [comment]
This is phenomenal!  Does this essentially replace our Jenkins setup for `linux` and `osx`?

**Comment by rmcgibbo** [comment]
I learned about it from https://pmelsted.wordpress.com/2015/10/14/building-binaries-for-bioinformatics/
on twitter. See http://phusion.github.io/holy-build-box/

**Comment by rmcgibbo** [comment]
I'm not really sure how it's different than just centos 5, exactly.

**Comment by mpharrigan** [comment]
It has a newer gcc

**Comment by rmcgibbo** [comment]
I don't think this has enough for OpenMM, because CUDA and OpenCL are a whole separate ball of wax, but otherwise I think it pretty much covers the same space as what the Jenkins servers do.

**Comment by jchodera** [comment]
I've actually built a docker image with CUDA and the AMD APP SDK in it:
https://hub.docker.com/r/jchodera/docker-core-linux-build-environment/

The Dockerfile is [here](https://github.com/FoldingAtHome/docker-core-linux-build-environment).

**Comment by jchodera** [comment]
For `linux`, could we just write a `Dockerfile` that starts with the `phusion/holy-build-box-64` and installs CUDA and the APP SDK, and have that automatically built by dockerhub?

That should just involve something like
```
FROM phusion/holy-build-box-64

# Install CUDA
ENV CUDA_HOME=/usr/local/cuda-7.0 CUDA_LIBPATH=/usr/local/cuda-7.0/lib64
ADD http://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64/cuda-repo-rhel6-7.0-28.x86_64.rpm .
RUN rpm -i --quiet cuda-repo-rhel6-7.0-28.x86_64.rpm
RUN yum clean expire-cache
RUN yum install -y --quiet cuda

# Install AMD SDK for OpenCL
ENV OPENCL_HOME=/opt/AMDAPPSDK-2.9-1 OPENCL_LIBPATH=/opt/AMDAPPSDK-2.9-1/lib/x86_64
ADD http://jenkins.choderalab.org/userContent/AMD-APP-SDK-linux-v2.9-1.599.381-GA-x64.tar.bz2 .
RUN tar xjf AMD-APP-SDK-linux-v2.9-1.599.381-GA-x64.tar.bz2
RUN ./AMD-APP-SDK-v2.9-1.599.381-GA-linux64.sh -- -s -a yes
```

**Comment by rmcgibbo** [comment]
Can you try doing that? I've never used dockerhub. Alternatively, could we just use that image instead? I don't remember if we want build off centos 5 or centos 6.

**Comment by jchodera** [comment]
Happy to try.  Give me a moment.

I believe we wanted to build off of CentOS 5 if at all possible, so I"m excited about also using the `phusion/holy-build-box-64` image for OpenMM F@h cores as well.

**Comment by rmcgibbo** [comment]
Yeah, that sounds good. I might merge this first, since this issue only
applies for OpenMM.

**Comment by jchodera** [comment]
Please do!

Is there a way to get it to skip OpenMM?

**Comment by jchodera** [comment]
I don't think it's possible to easily install CUDA on centos 5.x, but I realize that our `Vagrant` build VM was based on [centos 6.6](https://github.com/omnia-md/virtual-machines).

We might therefore be able to get by with using a tiny modification of the [fah openmm-core build docker image](https://hub.docker.com/r/jchodera/docker-core-linux-build-environment/) which is also based on centos 6.6.

I'll explore switching the docker image in a separate PR.

**Comment by rmcgibbo** [comment]
We could just use a separate CentOS 6 / CUDA image for OpenMM and the Centos 5 image for everything else. OpenMM is a special flower...

**Comment by jchodera** [comment]
That could work too, but would it be a separate travis branch, or a separate github repo?

**Comment by rmcgibbo** [comment]
Separate travis branch, probably.

**Comment by rmcgibbo** [comment]
Can you pause the Jenkins server? I want to file a new PR that bumps the build number on a bunch of recipes to make sure the Travis stuff is working, and don't want Jenkins and Travis to race each other.

**Comment by jchodera** [comment]
Paused!

**Pull request merged**
