### PR TITLE
BHMM release 0.6.1

### PR DESCRIPTION
**Pull request by franknoe**
hope this works...

### CODE REVIEW

**Comment by franknoe** [comment]
Failures are due to simpletraj (which is not used by bhmm, so this is independent).

**Comment by franknoe** [comment]
I'm not sure how to proceed with this. The changes in bhmm seem to be OK, but conda-build-all fails due to simpletraj which is *not* used by bhmm:

```
[conda-build-all] Error: one or more packages failed to build (win-32)
  simpletraj-0.3-py27_0.tar.bz2
Command exited with code 1
```

So what's the policy here? Can I merge the bhmm release or should we wait until the simpletraj release is fixed?

**Comment by jchodera** [comment]
Let me merge this and fix `simpletraj` in a separate PR!

**Comment by franknoe** [comment]
cheers!

Am 14/02/16 um 15:46 schrieb John Chodera:
>
> Let me merge this and fix |simpletraj| in a separate PR!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/omnia-md/conda-recipes/pull/438#issuecomment-183902388>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request merged**
