### PR TITLE
[assaytools] 0.3.0

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
@Lnaden : Any idea about this error?
https://travis-ci.org/omnia-md/conda-recipes/jobs/245064574#L2550-L2554
```
+brew cask install -y basictex
==> Deleting legacy cache at /Users/travis/Library/Caches/Homebrew/Casks
==> Migrating Caskroom from /opt/homebrew-cask/Caskroom to /usr/local/Caskroom.
==> Creating symlink from /usr/local/Caskroom to /opt/homebrew-cask/Caskroom.
Error: invalid option: -y
```

**Comment by Lnaden** [comment]
Short version: merge master into this PR

Long version:
Yes, there was was a change to the the way `homebrew-cask` handles options which are not supported anymore. See #786 where I "fixed" this but are now at the mercy of the CTAN servers for dumb reasons. So the version of the osx-build.sh script this PR is using is outdated and missing the fixes from that PR I made. You'll want to merge master into this to get the changes.

**Comment by Lnaden** [comment]
The `-y` options is no longer support for `homebrew-cask` and it seems to just imply its functionality now. Still a bit weird though

**Comment by jchodera** [comment]
> Short version: merge master into this PR

Looks like `master` is already merged. Did your change get un-done somehow?

**Comment by Lnaden** [comment]
Oh, I looked at the log more closely. Its effectively a `try...except` block now. That error was thrown so it went to the next option on the `elif`. Your actual error is here: https://travis-ci.org/omnia-md/conda-recipes/jobs/245064574#L2566-L2572

Which failed because the random CTAN server you targeted has not updated to the 2017 TeX library yet, its still on the 2016 one. You have to re-run the test until it passes now. Like I said, mercy of the CTAN servers....

**Pull request merged**
