### PR TITLE
ENH: Add skiplist feature

### PR DESCRIPTION
**Pull request by rmcgibbo**
Add feature to `conda-build-all` to implement #197. Following @jchodera's suggestion, there's no single central list. Each recipe directory is now permitted to contain a file called "skip.yaml" which can contain a list of platforms that are to be skipped.

Each skip specification is supposed look like `<PLATFORM_SPEC>_<PYTHON_SPEC>`, `<PLATFORM_SPEC>`, or `<PYTHON_SPEC>`, e.g. `win-32_py34`, `win-32`, or `py34`.

I also added some `skip.yaml` files to particular packages that don't support windows, python2, python3 or some particular subset, including

 - ambermini (no windows)
 - openmm (no windows on py2)
 - pyemma (no py3)
 - pytram (no py3)
 - pymbar (no py3)
 - sh (no windows)
 - subprocess32 (no windows or py3)

### CODE REVIEW

**Comment by jchodera** [comment]
This is awesome, but wouldn't it make more sense to have the lists contain which platforms are to be *built*?  Otherwise, all skiplists will have to be updated if some new platform (e.g. `py35`) is introduced.

Lack of a list would of course still mean that all combinations are attempted, as usual.

**Comment by rmcgibbo** [comment]
I don't like that as much. When a new platform comes out, why not take the presumption that we'll give it a try and see if things work? I like the idea that in general, we try all combinations. This is just about carving out limited exceptions to that.

**Comment by jchodera** [comment]
Sure, let's give that a try.

**Comment by peastman** [comment]
I notice you're having it skip all Windows builds for OpenMM.  What's the difficulty with building on Windows?  It would be really nice if we could get that working.

**Comment by rmcgibbo** [comment]
No, just skipping python2 on windows, since we don't support VS2008. https://github.com/omnia-md/conda-recipes/blob/master/openmm/skip.yaml

**Comment by peastman** [comment]
Ok, I missed that.  Thanks.

**Pull request merged**
