### PR TITLE
[ambermini] fix static gfortran dependencies on osx

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
This works on my machine, but may need more testing.

**Comment by rmcgibbo** [comment]
Making gcc a _runtime_ dependency on every platform seems like a heavy handed solution. Maybe only for osx?

**Comment by jchodera** [comment]
Good idea.  The `gcc` package isn't even available for `win`.

**Comment by rmcgibbo** [comment]
This works on my machine too.

**Comment by jchodera** [comment]
Thanks!  Shouldn't affect the `linux` or `win` builds then.

**Pull request merged**
