### PR TITLE
[openmm] 7.1rc1

### PR DESCRIPTION
**Pull request by jchodera**
cc: https://github.com/pandegroup/openmm/issues/1718

### CODE REVIEW

**Comment by jchodera** [comment]
I don't understand how or why, but these ended up being pushed to the `dev` channel instead of `rc`, so I've moved the manually.

**Comment by peastman** [comment]
And the Windows one ended up in the `main` channel!  I've fixed it.

**Comment by mpharrigan** [comment]
> I don't understand how or why, but these ended up being pushed to the dev channel instead of rc, so I've moved the manually.

Probably https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L260

**Comment by jchodera** [comment]
Ah! `upload`, if specified, should take precedence. We just have to reorder those if branches.

**Pull request merged**
