### PR TITLE
[thermotools] release 0.1.12

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by jchodera** [comment]
AppVeyor is failing with errors like this:
```
C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Miniconda\envs\_build\lib\site-packages\numpy\core\include -IC:\Miniconda\envs\_build\include -IC:\Miniconda\envs\_build\PC /Tcext/util/_util.c /Fobuild\temp.win32-2.7\Release\ext/util/_util.obj -O3 -std=c99
cl : Command line warning D9002 : ignoring unknown option '-O3'
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
_util.c
ext/util/_util.c(97) : error C2124: divide or mod by zero 
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

**Comment by rmcgibbo** [comment]
What is the purpose of adding back `preserve_egg_dir: True`? I would prefer to leave that out.

**Comment by cwehmeyer** [comment]
done

**Comment by rmcgibbo** [comment]
Thanks.

**Pull request merged**
