### PR TITLE
[openmm] bump build version to 1 to debug

### PR DESCRIPTION
**Pull request by jchodera**
Debugging. Do not merge.

### CODE REVIEW

**Comment by jchodera** [comment]
OK, it's not even printing any debug information about why it's skipping `openmm` in [the travis output](https://travis-ci.org/omnia-md/conda-recipes/jobs/132839367). Very confused.

**Comment by jchodera** [comment]
Here's the problem:
```
Considering recipes in the following order:
schema, alchemy, clusterutils, nglview, msmtools, svgwrite, paramz, pyhmc, scripttest, autograd, openblas, latexcodec, munkres, algopy, m4, sphinxcontrib-lunrsearch, freeglut, mingwpy, covar, parmed, mdtraj, pytram, pymbar, clapack, glew, termcolor, sh, eigen3, packmol, ecos, shiftx2, ccache, oset, pybtex, quadprog, docopt, silo, appdirs, theano, jom, simpletraj, fastcluster, scs, pdbfixer, pint, pyxb, cvxcanon, graphviz, hmmlearn, fftw3f, parse, osprey, cclib, swig, boost, subprocess32, sphinxcontrib-autodoc_doxygen, funcsigs, pytools, autoprotocol, parse_type, arpack, openbabel, cvxopt, python-coveralls, bison, pybtex-docutils, bhmm, nose-timer, openmmtools, rdkit, keras, assaytools, openmm-example-plugin, meld-plugin, numdifftools, thermotools, gpy, flex, pygraphviz, lomap, cvxpy, sphinxcontrib-bibtex, repex, behave, cpptraj, ambermini, fahmunge, deepchem, doxygen, pyemma, msmbuilder, openmoltools, ensembler, omnia, yank, msmb_data
```
`openmm` doesn't even appear in that list!

**Comment by jchodera** [comment]
Is there some sort of limit on how many things can be passed via command line globbing?

**Comment by jchodera** [comment]
OK, here is the issue (for @rmcgibbo and @marscher):

The command-line arguments for recipe paths are [being dropped when they are turned into a list of recipe names](https://travis-ci.org/omnia-md/conda-recipes/jobs/132839367#L258-L267):
```
+ /io/conda-build-all -vvv -- /io/LICENSE.txt /io/README.md /io/alchemy /io/algopy /io/ambermini /io/appdirs /io/appveyor.yml /io/arpack /io/assaytools /io/autograd /io/autoprotocol /io/behave /io/bhmm /io/bison /io/boost /io/ccache /io/cclib /io/clapack /io/clusterutils /io/conda-build-all /io/covar /io/cpptraj /io/cvxcanon /io/cvxopt /io/cvxpy /io/deepchem /io/devtools /io/docopt /io/doxygen /io/ecos /io/eigen3 /io/ensembler /io/fahmunge /io/fastcluster /io/fftw3f /io/flex /io/freeglut /io/funcsigs /io/glew /io/gpy /io/graphviz /io/hmmlearn /io/jom /io/keras /io/latexcodec /io/lomap /io/m4 /io/mdtraj /io/meld-plugin /io/mingwpy /io/msmb_data /io/msmbuilder /io/msmtools /io/munkres /io/nglview /io/nose-timer /io/numdifftools /io/omnia /io/openbabel /io/openblas /io/openmm /io/openmm-beta /io/openmm-example-plugin /io/openmmtools /io/openmoltools /io/oset /io/osprey /io/packmol /io/paramz /io/parmed /io/parse /io/parse_type /io/pdbfixer /io/pint /io/pybtex /io/pybtex-docutils /io/pyemma /io/pygraphviz /io/pyhmc /io/pymbar /io/pymol /io/python-coveralls /io/pytools /io/pytram /io/pyxb /io/quadprog /io/rdkit /io/repex /io/schema /io/scripttest /io/scs /io/sh /io/shiftx2 /io/silo /io/simpletraj /io/sphinxcontrib-autodoc_doxygen /io/sphinxcontrib-bibtex /io/sphinxcontrib-lunrsearch /io/subprocess32 /io/svgwrite /io/swig /io/termcolor /io/theano /io/thermotools /io/yank
EXECUTE:
verbose: 3
pythons: ['27', '34', '35']
numpys: ['1.10', '1.11']
channel_urls: ('omnia/label/main', 'omnia/label/dev', 'omnia/label/rc')
Considering recipes in the following order:
schema, alchemy, clusterutils, nglview, msmtools, svgwrite, paramz, pyhmc, scripttest, autograd, openblas, latexcodec, munkres, algopy, m4, sphinxcontrib-lunrsearch, freeglut, mingwpy, covar, parmed, mdtraj, pytram, pymbar, clapack, glew, termcolor, sh, eigen3, packmol, ecos, shiftx2, ccache, oset, pybtex, quadprog, docopt, silo, appdirs, theano, jom, simpletraj, fastcluster, scs, pdbfixer, pint, pyxb, cvxcanon, graphviz, hmmlearn, fftw3f, parse, osprey, cclib, swig, boost, subprocess32, sphinxcontrib-autodoc_doxygen, funcsigs, pytools, autoprotocol, parse_type, arpack, openbabel, cvxopt, python-coveralls, bison, pybtex-docutils, bhmm, nose-timer, openmmtools, rdkit, keras, assaytools, openmm-example-plugin, meld-plugin, numdifftools, thermotools, gpy, flex, pygraphviz, lomap, cvxpy, sphinxcontrib-bibtex, repex, behave, cpptraj, ambermini, fahmunge, deepchem, doxygen, pyemma, msmbuilder, openmoltools, ensembler, omnia, yank, msmb_data
```
By the time we get to [here](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L375) in `conda-build-all`, the recipes are already gone. So somehow this is a weird problem with command-line argument parsing.

I'm not so familiar with [the `argparse` syntax used for `recipe`](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L50-L55) to capture all the recipe paths.  But this is what is going wrong.

**Comment by marscher** [comment]
Wouldn't this then have happened before? I mean if none of the recipe paths are considered, no build would have been triggered ever since we introduced the 
change with the three labels?

**Comment by jchodera** [comment]
> Wouldn't this then have happened before? I mean if none of the recipe paths are considered, no build would have been triggered ever since we introduced the change with the three labels?

I'm not sure I understand.  What I am finding is that some of the provided recipe paths are dropped during the build.  If the majority of packages don't need to be updated or rebuilt, we may not have noticed this until we tried to build a package that was being dropped (like now).

**Comment by jchodera** [comment]
To be clear, here is the list of recipes we are providing on the command line:
> + /io/conda-build-all -vvv -- /io/LICENSE.txt /io/README.md /io/alchemy /io/algopy /io/ambermini /io/appdirs /io/appveyor.yml /io/arpack /io/assaytools /io/autograd /io/autoprotocol /io/behave /io/bhmm /io/bison /io/boost /io/ccache /io/cclib /io/clapack /io/clusterutils /io/conda-build-all /io/covar /io/cpptraj /io/cvxcanon /io/cvxopt /io/cvxpy /io/deepchem /io/devtools /io/docopt /io/doxygen /io/ecos /io/eigen3 /io/ensembler /io/fahmunge /io/fastcluster /io/fftw3f /io/flex /io/freeglut /io/funcsigs /io/glew /io/gpy /io/graphviz /io/hmmlearn /io/jom /io/keras /io/latexcodec /io/lomap /io/m4 /io/mdtraj /io/meld-plugin /io/mingwpy /io/msmb_data /io/msmbuilder /io/msmtools /io/munkres /io/nglview /io/nose-timer /io/numdifftools /io/omnia /io/openbabel /io/openblas /io/openmm /io/openmm-beta /io/openmm-example-plugin /io/openmmtools /io/openmoltools /io/oset /io/osprey /io/packmol /io/paramz /io/parmed /io/parse /io/parse_type /io/pdbfixer /io/pint /io/pybtex /io/pybtex-docutils /io/pyemma /io/pygraphviz /io/pyhmc /io/pymbar /io/pymol /io/python-coveralls /io/pytools /io/pytram /io/pyxb /io/quadprog /io/rdkit /io/repex /io/schema /io/scripttest /io/scs /io/sh /io/shiftx2 /io/silo /io/simpletraj /io/sphinxcontrib-autodoc_doxygen /io/sphinxcontrib-bibtex /io/sphinxcontrib-lunrsearch /io/subprocess32 /io/svgwrite /io/swig /io/termcolor /io/theano /io/thermotools /io/yank

And some of these get dropped, since `conda-build-all` thinks it only needs to check the following:
> schema, alchemy, clusterutils, nglview, msmtools, svgwrite, paramz, pyhmc, scripttest, autograd, openblas, latexcodec, munkres, algopy, m4, sphinxcontrib-lunrsearch, freeglut, mingwpy, covar, parmed, mdtraj, pytram, pymbar, clapack, glew, termcolor, sh, eigen3, packmol, ecos, shiftx2, ccache, oset, pybtex, quadprog, docopt, silo, appdirs, theano, jom, simpletraj, fastcluster, scs, pdbfixer, pint, pyxb, cvxcanon, graphviz, hmmlearn, fftw3f, parse, osprey, cclib, swig, boost, subprocess32, sphinxcontrib-autodoc_doxygen, funcsigs, pytools, autoprotocol, parse_type, arpack, openbabel, cvxopt, python-coveralls, bison, pybtex-docutils, bhmm, nose-timer, openmmtools, rdkit, keras, assaytools, openmm-example-plugin, meld-plugin, numdifftools, thermotools, gpy, flex, pygraphviz, lomap, cvxpy, sphinxcontrib-bibtex, repex, behave, cpptraj, ambermini, fahmunge, deepchem, doxygen, pyemma, msmbuilder, openmoltools, ensembler, omnia, yank, msmb_data

**Comment by marscher** [comment]
The drop decision is made on basis what has already been built, not the cmd args, right?

**Comment by jchodera** [comment]
This is happening *before* recipes are checked against anything.  Arguments are being dropped from the list of command-line arguments.

**Comment by jchodera** [comment]
Here, I've updated `conda-build-all` to spit out the command-line arguments it thinks it received.

**Comment by marscher** [comment]
Why do we have the double dashes before the recipes any ways?

**Comment by jchodera** [comment]
I have no idea.

**Comment by jchodera** [comment]
There are no problems when I run this locally on `osx`, by the way.

**Comment by rmcgibbo** [comment]
> Why do we have the double dashes before the recipes any ways?

http://unix.stackexchange.com/a/11382

**Comment by mpharrigan** [comment]
You could try running
```
$ xargs --show-limits
Your environment variables take up 2764 bytes
POSIX upper limit on argument length (this system): 2092340
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2089576
Size of command buffer we are actually using: 131072
```

**Comment by mpharrigan** [comment]
Although the number of arguments we're giving fits comfortably within those limits on my machine

**Comment by mpharrigan** [comment]
Found the problem! If we stop silently suppressing errors in `sort_recipes`

```
WARNING devtools Error: meta.yaml or conda.yaml not found in devtools
WARNING openmm Error: Invalid selector in meta.yaml line 13:
    - [ {{ os.environ.get('APPVEYOR', 'False') == 'True' }} ]

WARNING openmm-beta Error: Invalid selector in meta.yaml line 13:
    - [ {{ os.environ.get('APPVEYOR', 'False') == 'True' }} ]

WARNING pymol Error: Invalid selector in meta.yaml line 13:
    - [not (linux and py2)]
```

are all raised as `SystemExit` exceptions

**Comment by jchodera** [comment]
> Found the problem! If we stop silently suppressing errors in sort_recipes

How can we stop silently suppressing the errors?

And how can we fix this?  Should we pre-scan the directories for the existence of a `meta.yaml` file, or can we catch the exception?

**Comment by rmcgibbo** [comment]
Just log the exception.

**Comment by rmcgibbo** [comment]
And obviously fix the syntax errors.

**Comment by mpharrigan** [comment]
Note that that looks like a `jinja2` template that would render as True or False. Don't know if they or we got rid of templating of recipes

**Pull request merged**
