### PR TITLE
Remove || true to accurately report CI success/failure

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
fixes #690

**Comment by jchodera** [comment]
I see the [yank failure](https://travis-ci.org/omnia-md/conda-recipes/jobs/197523354#L3375-L3391
).

@Lnaden : Can you fix? Looks like it is [this issue](https://github.com/choderalab/protons/pull/70).

**Comment by Lnaden** [comment]
Once Yank 0.15.0 gets deployed, we can restart this travis job and the issue caused by yank should not error again. Sorry again about that

**Comment by Lnaden** [comment]
Restarted the travis builds, hopefully with 100% fewer yank errors this time

**Comment by Lnaden** [comment]
Travis ci builds are passing now

**Comment by jchodera** [comment]
Woohoo!

**Pull request merged**
