### PR TITLE
OSX travis build fixes: Update to CUDA 7.5, add latex

### PR DESCRIPTION
**Pull request by jchodera**
Addresses https://github.com/omnia-md/conda-recipes/issues/450

Also upgrades `osx` CUDA to 7.5

### CODE REVIEW

**Comment by jchodera** [comment]
I merged in your updates from #449 by hand, @rmcgibbo.  Hopefully I didn't break anything.

**Comment by jchodera** [comment]
I don't understand how this could have broken the `linux` build...

**Comment by jchodera** [comment]
Same problem with `osx`:
```
+./conda-build-all --check-against omnia omnia/label/pre LICENSE.txt Miniconda3-latest-MacOSX-x86_64.sh README.md alchemy algopy ambermini appdirs appveyor.yml arpack assaytools autograd behave bhmm bison boost ccache cclib clapack clusterutils conda-build-all covar cpptraj cvxcanon cvxopt cvxpy deepchem devtools docopt doxygen ecos ensembler fastcluster fftw3f flex freeglut glew hmmlearn jom keras latexcodec m4 mdtraj mingwpy msmbuilder msmtools munkres nglview nose-timer numdifftools omnia openbabel openblas openmm openmm-beta openmmtools openmoltools oset packmol parmed parse parse_type pdbfixer pint pybtex pybtex-docutils pyemma pyhmc pymbar pymol python-coveralls pytools pytram pyublas pyvisfile pyxb quadprog rdkit repex schema scripttest scs sh silo simpletraj sphinxcontrib-autodoc_doxygen sphinxcontrib-bibtex sphinxcontrib-lunrsearch subprocess32 svgwrite swig termcolor theano thermotools yank
usage: Build conda packages [-h]
                            [--check-against BINSTAR_USER [BINSTAR_USER ...]]
                            [--dry-run] [--upload UPLOAD] [--force]
                            [--no-test] [--python PYTHON_VER]
                            [--numpy NUMPY_VER] [-v]
                            RECIPE_PATH [RECIPE_PATH ...]
Build conda packages: error: the following arguments are required: RECIPE_PATH
```
Looks like the `--check-against` usage isn't correct.

**Comment by rmcgibbo** [comment]
merge in master. i made some commits to master after #449

**Comment by jchodera** [comment]
How is `--check-against` supposed to know which things that come after it are channels and which things are recipes?

**Comment by rmcgibbo** [comment]
argparse and nargs=+ do their job.

**Comment by rmcgibbo** [comment]
if you pull in the master branch's `conda-build-all` (560ffe4873cd62ea61ca1bd4ffaaea3b46c9326e), I think this'll work.

**Comment by jchodera** [comment]
Huh.  It says my branch is up-to-date:
```
[LSKI1497:omnia/conda-recipes/conda-recipes.jchodera] choderaj% git fetch upstream
[LSKI1497:omnia/conda-recipes/conda-recipes.jchodera] choderaj% git merge upstream/master
Already up-to-date.
```

**Comment by jchodera** [comment]
Your change [is there in my branch](https://github.com/jchodera/conda-recipes/blob/master/conda-build-all#L55).

**Comment by rmcgibbo** [comment]
mm. try putting a `--` in as a separator. e.g. `./conda-build-all --check-against omnia omnia/label/pre -- *` works on my laptop.

**Pull request merged**
