### PR TITLE
[WIP] Windows

### PR DESCRIPTION
**Pull request by rmcgibbo**
I'm working on the windows build. Making changes to the scripts here as I go.

Not ready to merge.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
1. Provision new Windows server 2012 VM
2. Download VS2008 express SP1 from the link here: http://stackoverflow.com/a/15319069/1079728
3. Download git for windows, and install all the unix-y components (3rd option)
4. Download and install Miniconda py27, 32-bit.
5. start the vs2008 command prompt, not the regular command prompt.
5. `conda install --yes conda-build binstar jinja2`

**Comment by rmcgibbo** [comment]
Things that I don't know how to build
- ambermini (needs fortran compiler)
- fftw
- cvxopt (doesn't compile w/ vs2008)

**Comment by rmcgibbo** [comment]
```
PS C:\Users\Administrator\conda-recipes> ls C:\Miniconda\conda-bld\win-32


    Directory: C:\Miniconda\conda-bld\win-32


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         1/10/2015  10:41 PM      10047 .index.json
-a---         1/10/2015  10:00 PM      24189 docopt-0.6.2-py27_0.tar.bz2
-a---         1/10/2015   9:55 PM      44147 ecos-1.0.5-py27_0.tar.bz2
-a---         1/10/2015   9:57 PM     142596 jpype1-0.5.7-np18py27_0.tar.bz2
-a---         1/10/2015   9:57 PM     142518 jpype1-0.5.7-np19py27_0.tar.bz2
-a---         1/10/2015   9:54 PM      29458 latexcodec-1.0.1-py27_0.tar.bz2
-a---         1/10/2015  10:03 PM    5439769 mdtraj-1.2.0-np18py27_0.tar.bz2
-a---         1/10/2015  10:04 PM    5439157 mdtraj-1.2.0-np19py27_0.tar.bz2
-a---         1/10/2015  10:38 PM     654752 msmbuilder-3.0.0-np18py27_0.tar.bz2
-a---         1/10/2015  10:39 PM     654661 msmbuilder-3.0.0-np19py27_0.tar.bz2
-a---         1/10/2015   9:55 PM      13908 munkres-1.0.7-py27_0.tar.bz2
-a---         1/10/2015  10:01 PM      53660 numdifftools-0.6.0-py27_0.tar.bz2
-a---         1/10/2015  10:12 PM        997 omnia-0.1-0.tar.bz2
-a---         1/10/2015  10:34 PM      57308 oset-0.1.3-py27_0.tar.bz2
-a---         1/10/2015  10:36 PM     475407 pybtex-0.18-py27_0.tar.bz2
-a---         1/10/2015  10:37 PM       6553 pybtex-docutils-0.2.0-py27_0.tar.bz2
-a---         1/10/2015  10:34 PM     462399 pyemma-1.0a3-py27_0.tar.bz2
-a---         1/10/2015  10:00 PM      68477 pyhmc-0.1.1-np18py27_0.tar.bz2
-a---         1/10/2015  10:00 PM      68459 pyhmc-0.1.1-np19py27_0.tar.bz2
-a---         1/10/2015  10:25 PM     110272 pymbar-2.1beta0-np18py27_0.tar.bz2
-a---         1/10/2015  10:25 PM     110241 pymbar-2.1beta0-np19py27_0.tar.bz2
-a---         1/10/2015   9:59 PM    3126711 pystallone-1.0.0b6-py27_0.tar.bz2
-a---         1/10/2015  10:41 PM       9023 repodata.json
-a---         1/10/2015  10:41 PM       1635 repodata.json.bz2
-a---         1/10/2015   9:50 PM      17797 scripttest-1.3-py27_0.tar.bz2
-a---         1/10/2015   9:58 PM      41657 scs-1.0.6-np18py27_0.tar.bz2
-a---         1/10/2015   9:58 PM      41667 scs-1.0.6-np19py27_0.tar.bz2
```

**Comment by kyleabeauchamp** [comment]
So we could probably ignore FFTW for 1.0, right?  It's only for the OpenMM PME plugin.

FWIW, it seems like Gromacs has some capability for automatically building FFTW on Windows via cmake (http://www.gromacs.org/Documentation/Installation_Instructions#Building_on_Windows).  Eventually, we can probably borrow some of their work.

**Comment by kyleabeauchamp** [comment]
If it simplifies our lives, I'm happy with providing reduced functionality under Windows--Windows user are accustomed to as much.

**Comment by rmcgibbo** [comment]
I also haven't gotten openmm. There's no `cmake` in the anaconda win-32 channels. I will try to get regular cmake from the windows download.

**Comment by rmcgibbo** [comment]
OpenMM builds correctly, but I have a DLL error when loading. The rpaths and stuff aren't set correctly.

**Comment by jchodera** [comment]
Since changes are spread throughout a number of recipes, it might be good to commit this later today even if it isn't complete coverage of `win` builds.

**Comment by rmcgibbo** [comment]
Sure. Everything in this is an improvement over the current master, so I'm good to merge.

**Comment by jchodera** [comment]
Thanks!

**Comment by rmcgibbo** [comment]
If you guys can get a windows VM configured as a jenkins slave, either on physical hardware or on EC2, that would be nice. EC2 is probably easier, because I can supply the AMI with all of the compilers and stuff installed. I'm sure there will be a ton of issues, but that will be a good place to hack from.

**Comment by jchodera** [comment]
Would the VM you sent us still be useful to try spinning up, or have you made lots of changes already?  If so, I might be able to give that a try from here on Sunday.

If you want to go the EC2 route, that might be something that @bas-rustenburg or @pgrinaway could try on Monday.

**Comment by rmcgibbo** [comment]
I have been working on EC2 today. But the one I sent you earlier would probably work fine too.

**Comment by jchodera** [comment]
Hm. How do you connect to the EC2 instance? Is there some way to allow me to briefly connect and install the Jenkins slave?

**Comment by rmcgibbo** [comment]
You use remote desktop. If you follow the wizard and select a windows image for your OS when setting up a new instance from the ec2 web console `https://console.aws.amazon.com/ec2/`, it's not too hard.

But in the end with jenkins, you probably want something slightly fancier, in which the jenkins server dynamically provisions a new VM when the job starts, and then throws it away when its finished. But that's more advanced.

**Comment by jchodera** [comment]
> But in the end with jenkins, you probably want something slightly fancier, in which the jenkins server dynamically provisions a new VM when the job starts, and then throws it away when its finished. But that's more advanced.

I think I know too little about EC2 to do this myself right now in any reasonable timeframe, but Jenkins does have virtualbox and vagrant setup/teardown capability.  Let me play with the vagrant win box you sent for a bit.

**Comment by rmcgibbo** [comment]
You're much better off using remote desktop. Windows is not designed to install stuff via the command line, so you really need to be able to click on things.

**Comment by rmcgibbo** [comment]
I think you can RDP to the vagrant box, but it's sketchier.

**Comment by rmcgibbo** [comment]
Anyways, it's not important for now that you get jenkins dynamically provisioning the VMs. That can come later. Easier to just start a VM from the console and then install the jenkins slave on it.

**Comment by jchodera** [comment]
I think this is beyond my capacity (both skill and time) at the moment, unfortunately.  I'll have to hand the win stuff off to @bas-rustenburg, who is in AMS until Mon 19 Jan (but who can spin something up on EC2 from there).

**Comment by peastman** [comment]
> So we could probably ignore FFTW for 1.0, right? It's only for the OpenMM PME plugin.

If you don't have FFTW, the CPU platform will get terrible performance on PME.

**Comment by jchodera** [comment]
I'm fine with prioritizing "it runs at all" over "it runs with good performance" for now.  We can just keep a list of known issues to be addressed.

**Pull request merged**
