### PR TITLE
Try to catch exception in conda-build-all

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Looks like this is working now, at least it got past the py34 jypye exception.

**Comment by rmcgibbo** [comment]
Do you know what the reason for the error in the first place is?

**Comment by kyleabeauchamp** [comment]
Issues in the jypye recipe build.sh.  However, I think this change is still worthwhile in that it prevents bad recipes from taking out our entire CI system.

**Comment by rmcgibbo** [comment]
> Issues in the jypye recipe build.sh.

Are you sure? This change just modifies loading the metadata, not the actually running of the build.sh

**Comment by kyleabeauchamp** [comment]
Look at the Travis output for this previous PR: https://travis-ci.org/omnia-md/conda-recipes/builds/47024208  

Here is a copypaste:

```
BUILD START: jpype1-0.5.7-np19py34_0

Fetching package metadata: ...

Solving package specifications: .

The following NEW packages will be INSTALLED:

numpy: 1.9.1-py34_0

openssl: 1.0.1k-0

python: 3.4.2-0

readline: 6.2-2

setuptools: 11.3.1-py34_0

sqlite: 3.8.4.1-0

system: 5.8-1

tk: 8.5.15-0

xz: 5.0.5-0

zlib: 1.2.8-0

Linking packages ...

[ COMPLETE ] |##################################################| 100%

Removing old work directory

Source cache directory is: /home/travis/miniconda/conda-bld/src_cache

Found source in cache: JPype1-0.5.7.tar.gz

Extracting download

Package: jpype1-0.5.7-np19py34_0

source tree in: /home/travis/miniconda/conda-bld/work/JPype1-0.5.7

+ echo 'building ./jpype1'

building ./jpype1

found egg: /home/travis/miniconda/envs/_build/lib/python3.4/site-packages/setuptools-11.3.1-py3.4.egg

compiling .pyc files...

number of files: 123

BUILD END: jpype1-0.5.7-np19py34_0

# If you want to upload this package to binstar.org later, type:

#

# $ binstar upload /home/travis/miniconda/conda-bld/linux-64/jpype1-0.5.7-np19py34_0.tar.bz2

#

# To have conda build upload to binstar automatically, use

# $ conda config --set binstar_upload yes

Traceback (most recent call last):

File "./conda-build-all", line 221, in <module>

main()

File "./conda-build-all", line 65, in main

execute(args, p)

File "./conda-build-all", line 202, in execute

metadata = MetaData(recipe)

File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 241, in __init__

assert isdir(path)

AssertionError
```

**Comment by rmcgibbo** [comment]
Well sure, so that implies sometimes that `recipe` is not a directory.

**Comment by rmcgibbo** [comment]
The issue is that `cluster-utils` is broken, not jpype.

```
-
-        try:
-            metadata = MetaData(recipe)
-        except AssertionError as e:
-            print("Skipping recipe due to issue grabbing metadata.")
-            print(e)
-            continue
+        print(recipe)
+        metadata = MetaData(recipe)
```

```
$ ./conda-build-all --python 27 --check-against omnia cluster-utils
Building recipes in the following order:
cluster-utils

cluster_utils
Traceback (most recent call last):
  File "./conda-build-all", line 223, in <module>
    main()
  File "./conda-build-all", line 65, in main
    execute(args, p)
  File "./conda-build-all", line 203, in execute
    metadata = MetaData(recipe)
  File "/Users/rmcgibbo/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 241, in __init__
    assert isdir(path)
AssertionError
```

**Comment by jchodera** [comment]
Roping in @danielparton to fix.

**Pull request merged**
