### PR TITLE
[thermotools] release 0.1.9

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
The lines `numpy >=1.7` should be changed to `numpy x.x`.

**Comment by cwehmeyer** [comment]
Done.

**Comment by rmcgibbo** [comment]
@cwehmeyer it doesn't compile properly:

```
gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda/envs/_build/lib/python3.5/site-packages/numpy/core/include -I/anaconda/envs/_build/include/python3.5m -c ext/bar/_bar.c -o build/temp.linux-x86_64-3.5/ext/bar/_bar.o -O3
gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda/envs/_build/lib/python3.5/site-packages/numpy/core/include -I/anaconda/envs/_build/include/python3.5m -c ext/util/_util.c -o build/temp.linux-x86_64-3.5/ext/util/_util.o -O3
ext/util/_util.c: In function '_logsumexp':
ext/util/_util.c:104:27: error: 'INFINITY' undeclared (first use in this function)
     if(0 == size) return -INFINITY;
                           ^
ext/util/_util.c:104:27: note: each undeclared identifier is reported only once for each function it appears in
ext/util/_util.c: In function '_logsumexp_kahan_inplace':
ext/util/_util.c:115:27: error: 'INFINITY' undeclared (first use in this function)
     if(0 == size) return -INFINITY;
                           ^
ext/util/_util.c: In function '_logsumexp_sort_inplace':
ext/util/_util.c:125:27: error: 'INFINITY' undeclared (first use in this function)
     if(0 == size) return -INFINITY;
                           ^
ext/util/_util.c: In function '_logsumexp_sort_kahan_inplace':
ext/util/_util.c:132:27: error: 'INFINITY' undeclared (first use in this function)
     if(0 == size) return -INFINITY;
                           ^
ext/util/_util.c: In function '_logsumexp_pair':
ext/util/_util.c:139:10: error: 'INFINITY' undeclared (first use in this function)
     if((-INFINITY == a) && (-INFINITY == b))
          ^
error: command 'gcc' failed with exit status 1
Command failed: /bin/bash -x -e /io/thermotools/build.sh
```

**Comment by cwehmeyer** [comment]
@rmcgibbo It looks like this build process does not support c99. Did that change recently?

**Comment by rmcgibbo** [comment]
The linux build machine is http://phusion.github.io/holy-build-box/. It has gcc 4.8, so c99 support is available. You might need to pass the proper command line flags to gcc though -- I'm not sure.
If you have a linux box with root available (needed to install docker), you can reproduce the build environment using the exact same docker image that's running on Travis with [this command](https://github.com/omnia-md/conda-recipes/blob/master/.travis.yml#L29-L31).

**Comment by rmcgibbo** [comment]
And this is the Dockerfile that the image is generated from, building of the holy-build-box image. https://github.com/rmcgibbo/centos5-build-box/blob/master/Dockerfile

**Pull request merged**
