### PR TITLE
Try -static-libgfortran to fix OSX issues in ambermini

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
@rmcgibbo  is this worth a try?  If so I'll merge and call in the jenkins

**Comment by rmcgibbo** [comment]
Does it work? I suspect it needs to be tested locally first. From e.g. [this SO thread](http://stackoverflow.com/questions/17910684/static-libgfortran-in-library-build) there are few other linker flags used as well.

**Comment by kyleabeauchamp** [comment]
I've also verified that the current PR works in the Centos VM, with the resulting package working on my Ubuntu machine.  

@rmcgibbo  I emailed a manual OSX build using this PR

**Comment by rmcgibbo** [comment]
```
$ cd ~/Downloads
$ tar -xzvf ambermini-14.0.1-1.tar.bz2
$ cd bin
$ otool -L sqm
sqm:
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
	/usr/local/gfortran/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/gfortran/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by rmcgibbo** [comment]
Not statically linked.

**Comment by rmcgibbo** [comment]
On my machine, using homebrew gfortran, and [this link](http://stackoverflow.com/questions/17590525/correct-way-to-statically-link-in-gfortran-libraries-on-osx), I got static linking to work.

But it required trashing the `libquadmath.dylib` file from my gfortran installation!
```
$ sudo mv /usr/local/lib/gcc/4.9/libquadmath.0.dylib /usr/local/lib/gcc/4.9/libquadmath.0.dylib.backup
```

```
$ cat Makefile
all:
	gfortran -static-libgfortran /usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/libquadmath.a \
	  -static-libgcc -lgfortran -o hello hello.f90
	otool -L hello
(3.4.2)rmcgibbo@DN0a22f7a9  ~/projects/conda-recipes/hello-world (3.4.2) ‹master*›
$ cat hello.f90
program hello
   print *, "Hello World!"
end program hello
(3.4.2)rmcgibbo@DN0a22f7a9  ~/projects/conda-recipes/hello-world (3.4.2) ‹master*›
$ make
gfortran -static-libgfortran /usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/libquadmath.a \
	  -static-libgcc -lgfortran -o hello hello.f90
otool -L hello
hello:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
(3.4.2)rmcgibbo@DN0a22f7a9  ~/projects/conda-recipes/hello-world (3.4.2) ‹master*›
$ ./hello
 Hello World!
```

**Comment by jchodera** [comment]
I imagine whatever solution we find here would also apply to the conda package insanity with `pymc` on `osx` as well.  (I'm struggling with that right now.)

**Pull request closed without merging**
