### PR TITLE
[msmtools] bump 1.1.2

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
one appveyor job failed for a github connection timeout...

**Comment by jchodera** [comment]
Hm, I can't seem to retrigger the appveyor job. Is this under @rmcgibbo's account?

**Comment by marscher** [comment]
I think so. Maybe we should create a team with at least the restart option for this job?

**Comment by marscher** [comment]
```
Fixing linking of /usr/lib/libSystem.B.dylib in /Users/travis/anaconda/envs/_build/lib/python3.4/site-packages/msmtools/estimation/dense/sampler_revpi.so

install_name_tool -add_rpath @loader_path/../../../../../ /Users/travis/anaconda/envs/_build/lib/python3.4/site-packages/msmtools/estimation/dense/sampler_revpi.so

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/travis/anaconda/envs/_build/lib/python3.4/site-packages/msmtools/estimation/dense/sampler_revpi.so (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

```

**Comment by rmcgibbo** [comment]
Can you check to see if you have more permissions on my appveyor now? I just added the "omnia-md/conda-recipes team" to something, but I don't really know what that did. The appveyor permissions UX is kind of confusing.

**Comment by rmcgibbo** [comment]
screenshot-1

**Comment by jchodera** [comment]
Hm, I still don't seem to have any way to restart the appveyor jobs...

**Comment by marscher** [comment]
Same situation here.

**Comment by marscher** [comment]
But your configuration seems to be sane. So maybe it is a problem on Appveyors side?

**Comment by marscher** [comment]
The OSX build seems to be broken for this reason:
https://github.com/conda/conda-build/issues/773

**Comment by rmcgibbo** [comment]
The only way to fix that is probably just change the setup.py file to pass `-headerpad_max_install_names` to clang when compiling.

**Comment by marscher** [comment]
what a hassle... Thanks Robert!

**Pull request merged**
