### PR TITLE
Fix cluster utils

### PR DESCRIPTION
**Pull request by rmcgibbo**
Reverts #121 and fixes the actual issue (the recipe directory name needs to match the package name -- one of them used a hyphen and the other an underscore).

### CODE REVIEW

**Comment by jchodera** [comment]
This ready to merge?

**Comment by rmcgibbo** [comment]
Wait till travis.

**Comment by rmcgibbo** [comment]
Okay. Passed the test. Merging.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
