### PR TITLE
[pyemma] version bump 2.2.

### PR DESCRIPTION
**Pull request by marscher**
Removed mdtraj win32 pytables workaround.

### CODE REVIEW

**Comment by jchodera** [comment]
Restarted the failed `osx` build.

**Comment by marscher** [comment]
Thank you!

**Comment by jchodera** [comment]
You've got some `pyemma` conflicts on `win`:
```
BUILD START: pyemma-2.2-np111py27_0
Fetching package metadata: .......... 
Solving package specifications: .Using Anaconda Cloud api site https://api.anaconda.org
... 
Error: The following specifications were found to be in conflict:
  - bhmm >=0.6,<0.7 -> numpy 1.10*|1.11*|1.9*
  - bhmm >=0.6,<0.7 -> scipy
  - matplotlib -> numpy 1.10*|1.11*|1.9*
  - mdtraj >=1.6 -> numpy 1.10*|1.11*|1.9*
  - mdtraj >=1.6 -> scipy
  - msmtools -> numpy 1.10*|1.9*|>=1.7
  - msmtools -> scipy
  - numpy 1.11*
  - python 2.7*
  - scipy -> numpy 1.10*|1.9*
  - thermotools >=0.2 -> msmtools >=1.1
  - thermotools >=0.2 -> numpy 1.10*|1.9*
  - thermotools >=0.2 -> scipy >=0.11
Use "conda info <package>" to see the dependencies for each package.
ERROR: File does not exist: C:\Miniconda\conda-bld\win-32\pyemma-2.2-np111py27_0.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
[conda-build-all] Error: one or more packages failed to build (win-32)
  msmbuilder-3.4.0-np111py27_0.tar.bz2
  pyemma-2.2-np111py27_0.tar.bz2

```

**Comment by marscher** [comment]
Yes, we are aware of that. See
https://github.com/omnia-md/conda-recipes/issues/526

**Comment by jchodera** [comment]
Are you going to have it skip `win` then?

**Comment by marscher** [comment]
We have to wait until Anaconda provides a build for win32-py27 for
recent Numpy for pytables, dependency of mdtraj.

**Comment by jchodera** [comment]
So should we mark this as `DO NOT MERGE`?

**Comment by marscher** [comment]
Please calm down. The builds for win-32-py27-np111 are missing. This is
not a reason not to merge.

**Comment by marscher** [comment]
The only downside for PyEMMA and MSMBuilder users on Windows-32 (which nobody uses actually, see the download numbers on anaconda.org), is that they have to use Numpy 1.10.

**Comment by jchodera** [comment]
Certainly not panicking---just wondering why you didn't add a skip to have the recipe skip `win py27 np111`.

**Comment by marscher** [comment]
I will add this for the Appveyor build not to fail.

**Comment by jchodera** [comment]
Thanks!  Apologies for having been unclear earlier in https://github.com/omnia-md/conda-recipes/pull/528#issuecomment-220031417

**Comment by marscher** [comment]
No problem! Thank you for the support :+1:

**Pull request merged**
