### PR TITLE
Updated omnia version to 1.0

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by jchodera** [comment]
Should this recipe have an explicit build number?

**Comment by kyleabeauchamp** [comment]
Probably doesn't matter.  If we change anything,  we should update the
minor version number.

**Comment by rmcgibbo** [comment]
The conda. build number defaults to zero. If you want to increment, you just set it to 1.

**Comment by rmcgibbo** [comment]
+1 to merge.

**Pull request merged**
