### PR TITLE
Update openmoltools recipe for 0.8 release

### PR DESCRIPTION
**Pull request by davidlmobley**
@andrrizzi - can you check?

Thanks.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Looks good! It looks like few dependencies can't be built on win64 (pdbfixer with python 3.4, and 4 other packages with python 3.6). @Lnaden is this expected?

**Comment by Lnaden** [comment]
We got OpenMM 7.1.1 moved to main and I have removed Python 3.4 from the supported versions as of this morning. I've re-triggered the Windows build, so hopefully they will pass now

**Comment by Lnaden** [comment]
Looks like the tests pass now!

**Comment by davidlmobley** [comment]
Excellent! @Lnaden - do you have permission to merge? I don't.

**Comment by Lnaden** [comment]
Done!

**Comment by davidlmobley** [comment]
Thank you!

**Pull request merged**
