### PR TITLE
Update to new release of openmoltools

### PR DESCRIPTION
**Pull request by davidlmobley**
Minor maintenance update that I need conda-installable for orion.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@Lnaden - should we merge this at this point, or wait til other fixes you're working on get merged? (I nee d this to roll out soon too, though the actual change it brings is super minor).

**Comment by Lnaden** [comment]
Once the main OpenMM package builds, I can prioritize PRs which are high priority like this one since most the other Python3.6 builds fail fast.

**Comment by Lnaden** [comment]
The log for this looks fine for open mol tools (when I can see it), merging this in.

**Comment by Lnaden** [comment]
The OpenMolTools have been built for Linux through Python 3.5, (inclusive). Python 3.6 requires OpenMM testing from `dev` to `main` channel first (many packages will have this issue), and the OSX and Windows builds are still in limbo right now.

Hopefully this at least gets you what you need for the short term

**Comment by davidlmobley** [comment]
Thanks!

**Pull request merged**
