### PR TITLE
Build numpy 1.11 packages

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
`scs` is failing because it can't find `-lgfortran` despite libgfortran being downloaded from conda as part of the build.

It works locally with conda build. Anyone have any ideas?

**Comment by jchodera** [comment]
Huh.  Now you've got a different error:
```
gcc -pthread -fno-strict-aliasing -fwrapv -Wall -O3 -DNDEBUG -fPIC -Ipyublas/include -I/anaconda/envs/_build/include -I/anaconda/envs/_build/lib/python2.7/site-packages/numpy/core/include -I/anaconda/envs/_build/include/python2.7 -c src/wrapper/main.cpp -o build/temp.linux-x86_64-2.7/src/wrapper/main.o -Wno-sign-compare
In file included from /anaconda/envs/_build/include/boost/lexical_cast/detail/inf_nan.hpp:35:0,
                 from /anaconda/envs/_build/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63,
                 from /anaconda/envs/_build/include/boost/lexical_cast/detail/converter_lexical.hpp:54,
                 from /anaconda/envs/_build/include/boost/lexical_cast/try_lexical_convert.hpp:42,
                 from /anaconda/envs/_build/include/boost/lexical_cast.hpp:32,
                 from /anaconda/envs/_build/include/boost/python/operators.hpp:19,
                 from /anaconda/envs/_build/include/boost/python.hpp:50,
                 from src/wrapper/main.cpp:16:
/anaconda/envs/_build/include/boost/math/special_functions/fpclassify.hpp:84:22: fatal error: quadmath.h: No such file or directory
 #include "quadmath.h"
                      ^
compilation terminated.
error: command 'gcc' failed with exit status 1
make: *** [all] Error 1
```
Maybe you need `gcc` as a dependency on `linux`?

**Comment by rmcgibbo** [comment]
I would just remove pyublas (the one that's broken above in @jchodera's comment). I added that as a depedency for something that I was using experimentally that didn't end up panning out, so there's no need for it to be in omnia.

**Comment by rmcgibbo** [comment]
(cc #491 to remove it)

**Comment by mpharrigan** [comment]
Can someone retrigger now that #491 is merged?

**Comment by rmcgibbo** [comment]
You may have to just rebase on master.

**Comment by mpharrigan** [comment]
Rebased

**Comment by mpharrigan** [comment]
```
collect2: error: ld returned 1 exit status

error: Command "gcc -pthread -shared -L/anaconda/envs/_build/lib -Wl,-rpath=/anaconda/envs/_build/lib,--no-as-needed build/temp.linux-x86_64-3.5/scsmodule.o build/temp.linux-x86_64-3.5/src/ctrlc.o build/temp.linux-x86_64-3.5/src/scs_version.o build/temp.linux-x86_64-3.5/src/cones.o build/temp.linux-x86_64-3.5/src/util.o build/temp.linux-x86_64-3.5/src/scs.o build/temp.linux-x86_64-3.5/src/linAlg.o build/temp.linux-x86_64-3.5/src/cs.o build/temp.linux-x86_64-3.5/linsys/common.o build/temp.linux-x86_64-3.5/linsys/direct/private.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_control.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_1.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_defaults.o build/temp.linux-x86_64-3.5/linsys/direct/external/SuiteSparse_config.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_order.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_postorder.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_valid.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_info.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_2.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_aat.o build/temp.linux-x86_64-3.5/linsys/direct/external/ldl.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_post_tree.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_dump.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_preprocess.o build/temp.linux-x86_64-3.5/linsys/direct/external/amd_global.o -L/anaconda/envs/_build/lib -L/anaconda/envs/_build/lib -lrt -lopenblas -lgfortran -lpython3.5m -o build/lib.linux-x86_64-3.5/_scs_direct.cpython-35m-x86_64-linux-gnu.so" failed with exit status 1
```

it installs libgfortran version 3 to the anaconda environment, includes that environment in the link path with the `-L` option, and then can't find `-lgfortran` ??

**Comment by jchodera** [comment]
Yep. The `libgfortran 3.0.0` package doesn't contain a library named `libgfortran.so`:
```
mski1776:Downloads choderaj$ tar ztf linux-64-libgfortran-3.0-0.tar.bz2 
info/files
info/index.json
info/meta
info/requires
lib/libgfortran.so.3
lib/libgfortran.so.3.0.0
```

**Comment by mpharrigan** [comment]
That doesn't matter (?)

**Comment by jchodera** [comment]
Good point. I bet we need the static library during compilation.

Have you tried adding `gcc` to the `build:` requirements?
```
mski1776:Downloads choderaj$ tar ztf linux-64-gcc-4.8.2-2.tar.bz2  | grep libgfortran
lib/gcc/x86_64-unknown-linux-gnu/4.8.2/libgfortranbegin.a
lib/gcc/x86_64-unknown-linux-gnu/4.8.2/libgfortranbegin.la
lib/libgfortran.a
lib/libgfortran.la
lib/libgfortran.so
lib/libgfortran.so.3
lib/libgfortran.so.3.0.0
lib/libgfortran.spec
```

**Comment by rmcgibbo** [comment]
I don't think you should need the static library.

**Comment by mpharrigan** [comment]
Update! I did have a `libgfortran.{a, so}` on my desktop after all (where it was working)
I don't have those on my laptops, and I can reproduce the failure.

**Comment by jchodera** [comment]
> I don't think you should need the static library.

I certainly don't know.

stackoverflow seems to think so, though---but, the internet:
http://askubuntu.com/questions/276892/cannot-find-lgfortran

**Comment by mpharrigan** [comment]
The gcc build-dep fix worked locally. I'll push those changes

**Comment by jchodera** [comment]
Woot!

**Comment by mpharrigan** [comment]
Getting closer...
## Linux

```
  bhmm-0.6.1-np111py34_0.tar.bz2
  pyemma-2.1-np111py27_0.tar.bz2
  pyemma-2.1-np111py34_0.tar.bz2
```

## Mac
Timeout

## Windows
```
[conda-build-all] Error: one or more packages failed to build (win-64)
  pyemma-2.1-np111py35_0.tar.bz2
  msmbuilder-3.4.0-np111py35_0.tar.bz2
```

```
[conda-build-all] Error: one or more packages failed to build (win-64)
  msmbuilder-3.4.0-np111py27_0.tar.bz2
  scs-1.2.2-np110py27_0.tar.bz2
  scs-1.2.2-np111py27_0.tar.bz2
  pyemma-2.1-np111py27_0.tar.bz2
```

and others

**Comment by jchodera** [comment]
@marscher and @franknoe : Can you take a look at the `linux` test failures in the travis logs?

**Comment by marscher** [comment]
Am 14.04.2016 um 03:57 schrieb John Chodera:
> @marscher <https://github.com/marscher> and @franknoe
> <https://github.com/franknoe> : Can you take a look at the |linux| test
> failures in the travis logs?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/omnia-md/conda-recipes/pull/490#issuecomment-209720325>
>
RuntimeError: Setuptools downloading is disabled in conda build. Be sure 
to add all dependencies in the meta.yaml 
url=https://pypi.python.org/simple/ordereddict/r

We are depending "mock", which itself depends on functools, which tries 
to drag in ordereddict. There is a mistake in the functools dependency 
declaration, since ordereddict is only needed for good old Python 2.6. 
I've opened a PR for an updated version of functools on omnia-recipes. 
So in theory this problem should be solved soon.

**Comment by marscher** [comment]
@mpharrigan try again, it works for me locally.

**Comment by mpharrigan** [comment]
I rebased this. If #517 is any indication, there are problems with `bhmm` still

**Comment by mpharrigan** [comment]
cc #517 let's not run the full suite of tests on `bhmm`

**Comment by jchodera** [comment]
> cc #517 let's not run the full suite of tests on bhmm

+1!

**Comment by jchodera** [comment]
`linux` passed!

There were some `osx` failures:
```
[conda-build-all] Error: one or more packages failed to build (osx-64)
  scs-1.2.2-np110py27_0.tar.bz2
  scs-1.2.2-np111py27_0.tar.bz2
  scs-1.2.2-np110py34_0.tar.bz2
  scs-1.2.2-np111py34_0.tar.bz2
  scs-1.2.2-np110py35_0.tar.bz2
  scs-1.2.2-np111py35_0.tar.bz2
  msmbuilder-3.4.0-np111py27_0.tar.bz2
  msmbuilder-3.4.0-np111py34_0.tar.bz2
  msmbuilder-3.4.0-np111py35_0.tar.bz2
```
I think the syntax to skip these would be
```YAML
  skip:
    - [osx and np == 110]
```
or `np == 111`.

**Comment by jchodera** [comment]
@mpharrigan when you get a chance, can you update/rebase and try again now that a few other issues are fixed?

**Comment by mpharrigan** [comment]
Rebased and removed this pr's changes to the scs build

**Comment by rmcgibbo** [comment]
+1 to merge this. The Travis build just timed out on one, but that's fine -- as the packages are built and uploaded the compute time will go down. For windows, there are still some skips to be added I assume due to some missing dependencies, but it's better IMO to handle those in subsequent PRs.

**Comment by jchodera** [comment]
Woo!

**Comment by mpharrigan** [comment]
Looks like all osx and linux builds succeeded. Some appveyor errors that we'll have to address. I'm testing the packages by entering an environment where I have packages of interest installed in their numpy 1.10 version (msmbuilder and mdtraj) and issuing

```
conda update -c omnia/label/rc --all
```

Note: `conda update -c omnia/label/rc msmbuilder` did not pull in all the new numpy packages.

**Pull request merged**
