### PR TITLE
Specify default upload label

### PR DESCRIPTION
**Pull request by marscher**
[conda-build-all] by default upload package to main. Recipes can specify label
    
    A meta.yaml can specify the channel to upload to within the extras section:
    
    extras:
      upload: rc
    
    Then all builds of this package will be uploaded specified channel only.
    
    Three default channels are now defined:
    1. main
    2. dev (development builds)
    3. rc (release candidates)

### CODE REVIEW

**Comment by marscher** [comment]
@jchodera I guess this is what we both had in mind?

**Comment by jchodera** [comment]
This is great!

**Comment by jchodera** [comment]
The travis output says that it is searching for the wrong channels, however:
```
channel_urls: ('omnia', 'omnia/label/pre', 'omnia/label/rc')
```
Any idea why it's not looking for `dev` instead of `pre`?

**Comment by marscher** [comment]
@jchodera I've resolved this issue you reported. The labels were given explicitly by invocation of conda-build-all, so it has overridden the defaults.

**Comment by jchodera** [comment]
Awesome, thanks!

**Comment by jchodera** [comment]
Will merge this, but tagging @mpharrigan that you'll need to add this label to the `mdtraj` recipe!

**Comment by mpharrigan** [comment]
Noted. Thanks guys!

**Pull request merged**
