### PR TITLE
Update ParmEd to 2.7.1

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
@davidlmobley -- this is what you need, right?

I'll also push 2.7.1 up to PyPI

**Comment by davidlmobley** [comment]
Yes, thanks so much, @swails !

**Comment by davidlmobley** [comment]
@jchodera - could you merge this? (Or someone else; I don't have access to do so).

I need the new ParmEd release so that tests will pass in `smarty`, among other things.

**Comment by jchodera** [comment]
@swails : I did this in https://github.com/omnia-md/conda-recipes/pull/656

Did that now work?

**Comment by jchodera** [comment]
2.7.1 is already build and posted: https://anaconda.org/omnia/parmed/files

Closing this.

**Comment by swails** [comment]
In my defense, this pr did come before #656 ;)

**Comment by jchodera** [comment]
Shoot, so sorry about that. I've just been catching up on things in reverse chronological order.

Would it be useful for you to have merge access, @swails?

**Comment by swails** [comment]
> Shoot, so sorry about that. I've just been catching up on things in reverse chronological order.

No worries -- the PRs were identical, so net effect is zero.

> Would it be useful for you to have merge access, @swails?

No, not useful.  Everything I do for Amber and OpenMM is strictly spare time (and some lunch hours).  For now that means almost exclusively maintaining ParmEd.  I don't have the bandwidth to manage additional responsibilities, so even if I had merge access I'd never exercise it.

**Pull request closed without merging**
