### PR TITLE
Don't run tests for pyhmc

### PR DESCRIPTION
**Pull request by mpharrigan**
There are a bunch of packages that aren't
available?

ref: https://github.com/rmcgibbo/pyhmc/blob/master/devtools/conda-recipe/meta.yaml

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I'm not sure I understand your question.

**Comment by mpharrigan** [comment]
```
    - rpy2
    - r-coda        # spectrum0, spectrum0.ar, effectiveSize
    - r-mcmc        # initseq()
    - r-batchmeans  # bm
```

don't seem to be available, and pyhmc wouldn't build because it couldn't run the tests.

**Comment by rmcgibbo** [comment]
Looks like it requires `onda config --add channels r` https://github.com/rmcgibbo/pyhmc/blob/master/.travis.yml

**Comment by kyleabeauchamp** [comment]
Is this good to go?

**Comment by mpharrigan** [comment]
@kyleabeauchamp I think we need to decide whether disabling the tests here is appropriate

@rmcgibbo the travis.xml looks pretty involved for getting the tests to run. Do you want to disable the tests here and relegate them to travis only?

**Comment by rmcgibbo** [comment]
Okay, fair enough.

**Pull request merged**
