### PR TITLE
[pyemma] bump version to 1.0.1

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
PS did you guy see the jpype issues on travis?  Not sure what's going on there

**Comment by marscher** [comment]
Not yet. You're referring to omnia/conda-recipes travis? Would be kind,
if you provide a url. Thank you

**Comment by marscher** [comment]
It seems travis builds jpype for python3, which is not compatible. Same applies for pyemma.

**Comment by rmcgibbo** [comment]
@marscher: do you know what the outlook for py3k support with the pyemma dependencies is (chiefly `jpype` I guess)?

**Comment by marscher** [comment]
for p3k we need another fork of jpype, which introduced py3k support.
Pystallone already handles this, so I need to provide another conda
recipe for the fork. But I fear pyemma has not yet been ported and it
will take some time to port/test it.

**Comment by kyleabeauchamp** [comment]
No worries, I think we're all happy with postponing py3k support.

**Pull request merged**
